### ISSUE TITLE
Question about NextPolish

### ISSUE THREAD

**Issue by wangzhennan14** [Nextomics/NextPolish#1]
Hi developer,
     I have some questions about NextPolish,please give me some suggestion:
     1. Is it using the base quality information when nextPolish run with Nanopore raw data?
     2. Your colleague told me that nextPolish was faster than Nanopolish, what do you improve that make nextPolish so faster?
     3. Does nextPolish just get the concensus sequence? Or others?
     4. How does nextPolish polish indel with Illumina data? Finally, the indel could be similar with Illumina data? Or nanopore data?
     Thank you very much!

**Comment by moold** [comment]
Hi,
1. NextPolish will use base quality information in illumina data, ignore  base quality information in long reads data.
3. yes.
2&4, please see NextPolish paper, which will be published soon.
