### ISSUE TITLE
Reduction in genome size after polishing

### ISSUE THREAD

**Issue by Shenu-Hudson** [Nextomics/NextPolish#100]
I noticed the genome size and other assembly statistics reducing after every round of polishing. Could someone explain to me why this is happening and how to handle this?

Initial genome size: 1092812176 bp
After round 1 polishing: 1092776966 (difference: 35210 bp )
After round2 polishing: 1092776883 (Round1-Round2: 83 bp)

Any help would be appreciated.

**Comment by moold** [comment]
Check whether the scaffold number of the raw genome and the polished genome is the same? If it is the same, that means the raw genome contains more insertion errors than deletion errors.

**Comment by Shenu-Hudson** [comment]
Thank you for your reply.

Scaffold numbers are the same for raw and polished genomes.

This assembly is a hybrid of Pacbio + optical mapping + Hic data. Can we
trust these insertion errors?


Regards,

Shenu Hudson B.
Junior Bioinformatician

*Nucleome Informatics Private Limited*
NKC Centre for Genomics Research, 2nd floor, 3 Cube towers,
2-93/8&9, White Field Rd, HITEC City, Hyderabad – 500081
Tel: 040 - 40114169
Email - ***@***.*** | Website: www.nucleomeinfo.com

**Comment by moold** [comment]
You can do some assessments, such as busco score or mapping RNA-SEQ data.
