### ISSUE TITLE
How to use Nextpolish on NextDenovo draft assembly

### ISSUE THREAD

**Issue by DrNavi** [Nextomics/NextPolish#105]
Hi, I am Dr. Naveed, i am new to perform Genome Assembly. I have nanopore long read data and I successfully used NextDenovo to draft a fungus assembly. I have got nd.asm.fasta file after assembly from NextDenovo, 11 contigs are generated. Now, I wanted to polish my draft assembly using NextPolish tool. What command I can use for polishing because when I saw the tutorial, I found this command is used to make input file for long read polishing,

**ls reads1.fq reads2.fa.gz > lgs.fofn**

However, I just got one output file from NextDenovo, which I want to polish..... 

I hope I made my question clear here..... I need guidance

**Comment by moold** [comment]
`reads1.fq reads2.fa.gz` are the nanopore long read data files, same input as NextDenovo

**Comment by DrNavi** [comment]
Dear Moold,

I only get only sequencing file from the company, "KI.fasta.tar.gz
