### ISSUE TITLE
MissAssembly Correction using NextPolish (Need Suggestions)

### ISSUE THREAD

**Issue by DrNavi** [Nextomics/NextPolish#107]
I am working on fungal genome assembly using long reads and I am getting lots of misassemblies. Assembly was made using NextDenovo, which made 11 contigs with lots of misassemblies. stats are as follows:

Largest contig  = 8126790
N50 = 5981938
misassemblies = 1939

I applied nextPolish as well but nothing improved. I m just wondering how can I improve this ?? The results of genome.nextpolish

Largest contig | 8126790
N50 | 5981938
misassemblies | 1939
# relocations | 638
# translocations | 1263
# inversions | 38
# misassembled contigs | 10
Misassembled contigs length | 43372515
# local misassemblies | 192

I am really confused how to improve it? looking forward for your suggestion

**Comment by moold** [comment]
It is hard to avoid misassemblies, but you can try other assembly tools first.
