### ISSUE TITLE
Adding Hisat2 instead of BWA

### ISSUE THREAD

**Issue by arslan9732** [Nextomics/NextPolish#109]
Hi,
Is it possible to incorporate hisat2 with flag `--no-spliced-alignment` instead of bwa inside NextPolish? Because hisat2 is faster enough as compared to bwa.

**Comment by moold** [comment]
Hi, you can also use your own alignment pipeline, see [here](https://nextpolish.readthedocs.io/en/latest/QSTART.html#quick-start). In this case you can use any mapping tools.
