### ISSUE TITLE
The completeness evaluated by BUSCO

### ISSUE THREAD

**Issue by yilunhuangyue** [Nextomics/NextPolish#11]
Hi, Thanks for developing the tools. I compared the result of Nextpolish and pilon. The error rate of polished result by Nextpolish were lower than that of pilon, however, the completeness of BUSCO were also slightly reduced compared with pilon. Could you please provide some information  about this? Thanks a lot.

**Comment by moold** [comment]
Could you provide the config file and how about the genome size?

**Comment by yilunhuangyue** [comment]
the genome size is about 300M and the config siz is like this:
task = 1212
genome = genome.fa
sgs_fofn = sgs.fofn

**Comment by moold** [comment]
I guess you ran pilon with bwa, while run NextPolish with minimap2, see FAQ vi. You can try to use option: `sgs_options = -max_depth 100 -bwa`. Our tests shown the accuracy of polished genomes will less than minimap2 in some situations.

**Comment by yilunhuangyue** [comment]
Yes, i run Nextpolish with minimap2. I will try use bwa and compared the result. Thank you~
