### ISSUE TITLE
error of generate_lqseqs_from_cluster

### ISSUE THREAD

**Issue by fangdm** [Nextomics/NextPolish#110]
Hi, I got the error information as follow :

[INFO] 2023-03-15 13:47:31,472 Start a corrected worker in 2647 from parent 2587
python3.9: ctg_cns.c:601: generate_lqseqs_from_cluster: Assertion `lqseq->start == clu->r.s' failed.
[INFO] 2023-03-15 13:52:03,905 Start a corrected worker in 3468 from parent 2587

and then the process was suspended.
After checking, only one contig had got the exeption and all the others are OK.
how can i solve the problem?

thank you.

version: nextPolish v1.3.1
The error generated in 04.polish.ref.sh.work/ while running the script nextpolish2.py.

**Comment by moold** [comment]
The easiest way is to copy the original contig into the final result

**Comment by fangdm** [comment]
Thank you.

so, why did it happen? i check the sequence, it was not the longest one, it had no special characterand, it had the similar GC content compare with others, also it had the mapping result.
