### ISSUE TITLE
User defined alignment pipeline for short- and long-reads

### ISSUE THREAD

**Issue by RenscoHogers** [Nextomics/NextPolish#113]
**Question or Expected behavior**
I am currently running into an issue when running NextPolish using short- and long-reads. It seems that the process is killed during samtools sort, seemingly due to too little memory when running through SLURM. I would like to solve this by running my own alignment pipeline, but there are only examples for running your pipeline for short-reads or long-reads, not both. Is it as simple as combining both in one script, or do you have a better suggestion?

**Operating system**
Which operating system and version are you using?
Ubuntu 20.04 LTS

**GCC**
What version of GCC are you using?
11.2.0

**Python**
What version of Python are you using?
3.10.8

**NextPolish**
What version of NextPolish are you using?
1.4.1

**Comment by moold** [comment]
You can try to polish the genome twice using long-reads, and then polish the genome (the polishing result with long-reads) twice using short-reads. This is the same as the default strategy used by `NextPolish`.

**Comment by RenscoHogers** [comment]
Sorry for the late reply, but I have created my own pipeline based on your suggestions and the information on GitHub and it works! Thanks for the help.
