### ISSUE TITLE
[question] combine with medaka or not?

### ISSUE THREAD

**Issue by JWDebler** [Nextomics/NextPolish#114]
In the past my long read polishing pipeline was:

1 x racon followed by 1 x medaka

I was wondering if you have any data on potential combinations of polishing tools.

Is there anything nextpolish does better/worse than other polishing tools? Does it make sense to combine them or run nextpolish only?
Cheers,
Johannes

**Comment by moold** [comment]
If you don't have short reads, I think medaka (long) is ok. If you have short reads, you can try  medaka (long) + nextpolish (short)  or nextpolish (long + short reads)

**Comment by JWDebler** [comment]
I ran a quick polisher combination comparison. In this case it looks like nextpolish followed by medaka (using long reads only) is the winner by a tiny margin.

![image](https://github.com/Nextomics/NextPolish/assets/4354282/d82cec22-9920-43ce-bc1c-d19ad7533846)

**Comment by moold** [comment]
Nice benchmark
