### ISSUE TITLE
run nextplolish2.py sleep

### ISSUE THREAD

**Issue by wang-zewen** [Nextomics/NextPolish#115]
When running nextpolish2.py, the task remains in a sleep state after submission, and the thread count shows as 0.

nextpolish2.py -sp -p 10 -g input.genome.fasta -b input.genome.fasta.blc -i 1 -l lgs.sort.bam.list -r ont -o genome.nextpolish.part001.fasta

**Comment by moold** [comment]
Try to kill it and rerun.

**Comment by wang-zewen** [comment]
The reason for the process to sleep is that some contig cannot obtain the result during the execution of the line c_seq = P.ctg_cns_core(CFG, REFS.contents.ref[n], bam_list). How can we solve this problem?

**Comment by moold** [comment]
Could you extract the sequences and bam of  `some contigs` you mentioned and then send to me? so I can reprocude this bug.

**Comment by wang-zewen** [comment]
https://drive.google.com/file/d/1Zb9nvHnpih3mr6_bjwvKODk3Ve1UOupN/view?usp=sharing
https://drive.google.com/file/d/1bqtCf9ghjbaKSw5G4Ajbxd7AbqvsPpPS/view?usp=sharing
you can download the error ctg file and bam file using the link

**Comment by moold** [comment]
Thanks, but the bam file is too large to download, could you please extract the bam of the contigs that failed to polish. You can use `samtools` like this:
```
samtools  view -b all.bam conitg_name > conitg_name.bam
```

**Comment by wang-zewen** [comment]
Hi, This is the new file
https://drive.google.com/file/d/1K0meLhaBQ7rACd8tmNgL3lKdximk2fJ_/view?usp=sharing, https://drive.google.com/file/d/1MW0DbvsRzjehsHu1vj8EQSYLRBXK0dhX/view?usp=sharing, https://drive.google.com/file/d/1bqtCf9ghjbaKSw5G4Ajbxd7AbqvsPpPS/view?usp=sharing

**Comment by moold** [comment]
The reads from your bam file contain lots of non-ATGC bases, so you need to remove these reads...

**Comment by wang-zewen** [comment]
ok. Thank you.
