### ISSUE TITLE
Support for paired and unpaired short reads input

### ISSUE THREAD

**Issue by berombau** [Nextomics/NextPolish#12]
Does NextPolish support a mixture of paired and unpaired short reads as input like Pilon (--frags and --unpaired)?

The syntax in https://github.com/Nextomics/NextPolish/blob/master/doc/OPTION.md doesn't hint to this functionality.

**Comment by moold** [comment]
Currently, NextPolish does not support a mix of paired and unpaired reads as input, but it supports using paired or unpaired reads only as input ( the option: `-unpaired`). While, I strongly suggest use  paired  reads to polish the genome, which can decrease the incorrect mapping in the repeat regions and improve the polishing accuracy  of these regions.

**Comment by berombau** [comment]
OK, thank you for the clarification.
