### ISSUE TITLE
zlib.h not found error

### ISSUE THREAD

**Issue by BRNiu** [Nextomics/NextPolish#127]
**Describe the bug**
An error occured while making nextPolish installed.

**Error message**
mkdir /data/home/assembly/software/NextPolish/bin
make -C util;
make[1]: Entering directory `/data/home/assembly/software/NextPolish/util'
gcc -Wall -O3 -s -pthread -o seq_split seq_split.c thpool.c -lz 
seq_split.c:5:18: fatal error: zlib.h: No such file or directory
 #include <zlib.h>
                  ^
compilation terminated.
make[1]: *** [seq_split] Error 1
make[1]: Leaving directory `/data/home/assembly/software/NextPolish/util'
make: *** [all] Error 2

**Operating system**
Which operating system and version are you using?
You can use the command `lsb_release -a` to get it.

**GCC**
gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) 

**Python**
Python 3.12.0

**NextPolish**
nextPolish v1.4.1

**Comment by moold** [comment]
see [here](https://www.google.com/search?q=zlib.h%3A+No+such+file+or+directory&oq=zlib.h%3A+No+such+file+or+directory&gs_lcrp=EgZjaHJvbWUyBggAEEUYOdIBBzI3MWowajGoAgCwAgA&sourceid=chrome&ie=UTF-8)
