### ISSUE TITLE
During the execution of samtools index, I encountered an error: "invalid option -- '@'"

### ISSUE THREAD

**Issue by jiuyaojiaonini** [Nextomics/NextPolish#131]
When I checked the error message here: 00.lgs_polish/03.merge.bam.sh.work/merge_bam1/, I found that there was an invalid parameter prompt when building the bam index: invalid option – ‘@’, and I’m not sure how to resolve this.

**Comment by jiuyaojiaonini** [comment]
I’m delighted to receive your reply, thank you! In fact, I checked and found that the version of samtools in the conda environment where NextPolish is installed is 1.3.1, which does not have the -@ parameter. However, version 1.11 of samtools does have the -@ parameter. Are you suggesting that I need to upgrade the samtools in the conda environment to version 1.11?

**Comment by moold** [comment]
Yes

**Comment by jiuyaojiaonini** [comment]
Oki! Thank you very much~
