### ISSUE TITLE
How does NextPolish handle short-reads mapping to multiple parts of the genome?

### ISSUE THREAD

**Issue by RenscoHogers** [Nextomics/NextPolish#133]
Hi,

I am currently using NextPolish for a genome in which we are looking at a particular repeat region. Now I am wondering what NextPolish does when short-reads map to multiple parts of the genome. Does it polish all these regions to become the same, or does it skip these regions, or is there a different method at play?

Thanks in advance.

**Comment by moold** [comment]
It only uses the primary alignment of each read, regardless of repeats.
