### ISSUE TITLE
Is there any option for unpolished Ns stay as Ns?

### ISSUE THREAD

**Issue by hyunjokoo** [Nextomics/NextPolish#140]
Hello,

I see that NextPolish version 1.3.1 says that it has this feature.
"Delete reads containing N bases"

I think that NextPolish now does not keep N even though there is no supporting read for the NNNNNNNN region.

When I checked using IGV after polishing, I see that all the N characters were changed to mainly C, including just several A. There were no supporting reads for this region, and 100 N characters were all changed to mostly C.

Is there any option that NextPolish keep unplished N as N?

I want to keep the gap region (written in 100 N characters) still gap region written in N, if the gap was not really polished.

Thank you.

HJK

**Comment by moold** [comment]
Sorry, you should write a small script to do this task, see [here](https://nextpolish.readthedocs.io/en/latest/QSTART.html#limitations). and welcome to pull a request.
