### ISSUE TITLE
make：No reaction

### ISSUE THREAD

**Issue by chenji333** [Nextomics/NextPolish#15]
Hello,I have a problem executing "make".as follows:
[Zahng@fat01 NextPolish] $ make
mkdir /lustre/Zahng/biosoft/NextPolish/bin
make -C util;
make[1]: Entering directory `/lustre/Zahng/biosoft/NextPolish/util'
gcc -Wall -O3 -fvisibility=hidden -s -pthread -o seq_split seq_split.c thpool.c -lz 

Staying at this step, nothing happens
Excuse me, will this step last for a long time?

**Comment by moold** [comment]
Nope, it should be very quickly.

**Comment by chenji333** [comment]
So far, this interface has remained. May I ask which part is the problem?

**Comment by moold** [comment]
What is your system and gcc version?

**Comment by chenji333** [comment]
1：Linux version 3.10.0-327.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.3 20140911 (Red Hat 4.8.3-9) (GCC) ) #1 SMP Thu Nov 19 22:10:57 UTC 2015

2：gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC)

Is it possibly related to my version of gcc?

**Comment by moold** [comment]
Could you try to remove the option `-Wall -O3 -fvisibility=hidden -s` in `util/Makefile`, and make again?
