### ISSUE TITLE
Parameters for PacBio long reads polishing

### ISSUE THREAD

**Issue by GRGong** [Nextomics/NextPolish#16]
Hi,
I have ~100x depth PacBio reads and a genome file generated by Flye. And I want to use NextPolish to improve my assembly. However, the parameters in the example run.cfg seems to be used for Nanopore data. So, I want some advice about parameters for PacBio data.

Thx!
gr

**Comment by moold** [comment]
Hi, change `lgs_minimap2_options = -x map-ont`  to `lgs_minimap2_options = -x map-pb`.
