### ISSUE TITLE
The example script for local polishing has some mistakes.

### ISSUE THREAD

**Issue by GRGong** [Nextomics/NextPolish#17]
The example "https://github.com/Nextomics/NextPolish/blob/master/doc/bwa.sh" has two mistakes.
1.  line2, "polished_round" should be "round" which matches line7.
2.  line7, "for i in {1..${round}}" is a wrong syntax which will only run 1 round, it should be "for ((i=1;i<=round;i++))" or sth. else.

**Comment by moold** [comment]
Thank you so much, I have updated this file.
