### ISSUE TITLE
Error when installed

### ISSUE THREAD

**Issue by wangzhennan14** [Nextomics/NextPolish#2]
Hi,
    When I installed NextPolish-1.0.3, there were some errors as follow:
    
![微信图片_20190725100149](https://user-images.githubusercontent.com/17285718/61840418-b7fa4a00-aec3-11e9-92c2-c873a686b672.jpg)
    Could you give me some advices to solve it? Thank you very much!
                                                                                                             Wang

**Comment by moold** [comment]
It seems this is the error when installing samtools, I think you can install [samtools](https://github.com/samtools/samtools) separately, and then copy the samtools exe file to NextPolish/bin/.
BTW, to avoid this errr when installing NextPolish, you can change this line:
`PROGS = seq_split seq_count bwa_ samtools_ minimap2_`
to 
`PROGS = seq_split seq_count bwa_ minimap2_`
 in file util/Makefile
