### ISSUE TITLE
Genome size halved after polishing

### ISSUE THREAD

**Issue by SYSU-SinLee** [Nextomics/NextPolish#20]
Dear developer,

I used both Pacbio and Illumina filtered reads for polishing and specified the genome size in the run.cfg file. But the final polished genome size was about half of the input one. I'm wondering if there are anything wrong in my cfg file showed below. I'll appreciate it if you have any suggestion.

Best regards,
Sen

[General]
job_type = local
job_prefix = nextPolish
task = 551212
rewrite = no
rerun = 3
parallel_jobs = 2
multithread_jobs = 5
genome = ./in.pacbio.hic.fa
genome_size = 270M
workdir = ./bg.20200410
polish_options = -p {multithread_jobs}

[sgs_option]
sgs_fofn = ./sgs.fofn
sgs_options = -max_depth 300 -bwa 

[lgs_option]
lgs_fofn = ./lgs.fofn
lgs_options = -min_read_len 10k -max_read_len 150k -max_depth 150
lgs_minimap2_options = -x map-pb -t {multithread_jobs}

[polish_options]
-min_map_quality 30

**Comment by moold** [comment]
Hi, Could you check whether NextPolish has finished? Could you paste the log to here? BTW, what is the size of your genome file (` ./in.pacbio.hic.fa`)?

**Comment by SYSU-SinLee** [comment]
> Hi, Could you check whether NextPolish has finished? Could you paste the log to here? BTW, what is the size of your genome file (` ./in.pacbio.hic.fa`)?

Thanks for your quick reply, the size of the genome file is 262Mb while the size of final polished genome (genome.nextpolish.part001.fasta) is 131Mb.

Log:
[INFO] 2020-04-10 14:56:33,199 start...
[INFO] 2020-04-10 14:56:33,200 logfile: pid434326.log.info
[INFO] 2020-04-10 14:56:33,204 scheduled tasks:
[5, 5, 1, 2, 1, 2]
[INFO] 2020-04-10 14:56:33,205 options: 
[INFO] 2020-04-10 14:56:33,205 {'polish_options': '-p 5', 'rewrite': 0, 'job_prefix': 'nextPolish', 'job_type': 'local', 'cluster_options': '', 'snp_valid': '/data/users/analysis/polish/in_raw_data/./in.20200410/%02d.snp_valid', 'kmer_count': '/data/users/analysis/polish/in_raw_data/./in.20200410/%02d.kmer_count', 'lgs_fofn': '/data/users/analysis/polish/in_raw_data/./lgs.fofn', 'sgs_max_depth': '300', 'align_threads': 5, 'sgs_block_size': 500000000, 'lgs_max_read_len': '150k', 'parallel_jobs': '2', 'multithread_jobs': '5', 'snp_phase': '/data/users/analysis/polish/in_raw_data/./in.20200410/%02d.snp_phase', 'genome': '/data/users/analysis/polish/in_raw_data/./in.pacbio.hic.fa', 'genome_size': 270000000, 'workdir': '/data/users/analysis/polish/in_raw_data/./in.20200410', 'cleantmp': 0, 'sgs_align_options': 'bwa mem -p  -t 5', 'sgs_unpaired': '0', 'sgs_fofn': '/data/users/analysis/polish/in_raw_data/./sgs.fofn', 'lgs_polish': '/data/users/analysis/polish/in_raw_data/./in.20200410/%02d.lgs_polish', 'sgs_use_duplicate_reads': 0, 'score_chain': '/data/users/analysis/polish/in_raw_data/./in.20200410/%02d.score_chain', 'task': [5, 5, 1, 2, 1, 2], 'lgs_max_depth': '60', 'lgs_block_size': 500000000, 'lgs_minimap2_options': '-x map-pb -t 5', 'rerun': 3, 'lgs_min_read_len': '1k'}
[INFO] 2020-04-10 14:56:33,221 step 0 and task 5 start:
[INFO] 2020-04-10 14:56:33,238 analysis tasks done
[INFO] 2020-04-10 14:56:33,264 total jobs: 4
[INFO] 2020-04-10 14:56:33,280 Throw jobID:[434329] jobCmd:[/data/users/analysis/polish/in_raw_data/in.20200410/00.lgs_polish/01.db_split.sh.work/db_split0/nextPolish.sh] in the local_cycle.
[INFO] 2020-04-10 14:56:33,787 Throw jobID:[434339] jobCmd:[/data/users/analysis/polish/in_raw_data/in.20200410/00.lgs_polish/01.db_split.sh.work/db_split1/nextPolish.sh] in the local_cycle.
[INFO] 2020-04-10 14:56:46,436 Throw jobID:[434363] jobCmd:[/data/users/analysis/polish/in_raw_data/in.20200410/00.lgs_polish/01.db_split.sh.work/db_split2/nextPolish.sh] in the local_cycle.
[INFO] 2020-04-10 14:57:43,880 Throw jobID:[434438] jobCmd:[/data/users/analysis/polish/in_raw_data/in.20200410/00.lgs_polish/01.db_split.sh.work/db_split3/nextPolish.sh] in the local_cycle.
[INFO] 2020-04-10 15:58:53,538 db_split done
[INFO] 2020-04-10 15:58:53,539 analysis tasks done
[INFO] 2020-04-10 15:58:53,541 total jobs: 2
[INFO] 2020-04-10 15:58:53,542 Throw jobID:[444076] jobCmd:[/data/users/analysis/polish/in_raw_data/in.20200410/00.lgs_polish/02.map.ref.sh.work/map_genome0/nextPolish.sh] in the local_cycle.
[INFO] 2020-04-10 15:58:54,045 Throw jobID:[444083] jobCmd:[/data/users/analysis/polish/in_raw_data/in.20200410/00.lgs_polish/02.map.ref.sh
.work/map_genome1/nextPolish.sh] in the local_cycle.
[INFO] 2020-04-10 15:59:58,593 align_genome done
[INFO] 2020-04-10 15:59:58,594 analysis tasks done
[INFO] 2020-04-10 15:59:58,595 total jobs: 1
[INFO] 2020-04-10 15:59:58,595 Throw jobID:[444215] jobCmd:[/data/users/analysis/polish/in_raw_data/in.20200410/00.lgs_polish/03.merge.bam.
sh.work/merge_bam0/nextPolish.sh] in the local_cycle.
[INFO] 2020-04-10 16:00:00,594 merge_bam done
[INFO] 2020-04-10 16:00:00,625 analysis tasks done
[INFO] 2020-04-10 16:00:00,627 total jobs: 2
[INFO] 2020-04-10 16:00:00,628 Throw jobID:[444234] jobCmd:[/data/users/analysis/polish/in_raw_data/in.20200410/00.lgs_polish/04.polish.ref
.sh.work/polish_genome0/nextPolish.sh] in the local_cycle.
[INFO] 2020-04-10 16:00:01,131 Throw jobID:[444247] jobCmd:[/data/users/analysis/polish/in_raw_data/in.20200410/00.lgs_polish/04.polish.ref
.sh.work/polish_genome1/nextPolish.sh] in the local_cycle.
[INFO] 2020-04-10 16:00:28,937 polish_genome done
[INFO] 2020-04-10 16:00:28,937 step 1 and task 5 start:
[INFO] 2020-04-10 16:00:28,938 analysis tasks done
[INFO] 2020-04-10 16:00:28,940 total jobs: 1
[INFO] 2020-04-10 16:00:28,941 Throw jobID:[444320] jobCmd:[/data/users/analysis/polish/in_raw_data/in.20200410/01.lgs_polish/01.merge.ref.
sh.work/merge_ref0/merge_ref.sh] in the local_cycle.
[INFO] 2020-04-10 16:00:29,948 merge_ref done
[INFO] 2020-04-10 16:00:29,949 analysis tasks done
[INFO] 2020-04-10 16:00:29,951 total jobs: 2
[INFO] 2020-04-10 16:00:29,952 Throw jobID:[444328] jobCmd:[/data/users/analysis/polish/in_raw_data/in.20200410/01.lgs_polish/02.index.ref.
sh.work/index_genome0/nextPolish.sh] in the local_cycle.
[INFO] 2020-04-10 16:00:30,455 Throw jobID:[444336] jobCmd:[/data/users/analysis/polish/in_raw_data/in.20200410/01.lgs_polish/02.index.ref.
sh.work/index_genome1/nextPolish.sh] in the local_cycle.
[INFO] 2020-04-10 16:00:41,449 index_genome done
[INFO] 2020-04-10 16:00:41,450 analysis tasks done
[INFO] 2020-04-10 16:00:41,452 total jobs: 2
[INFO] 2020-04-10 16:00:41,453 Throw jobID:[444364] jobCmd:[/data/users/analysis/polish/in_raw_data/in.20200410/01.lgs_polish/03.map.ref.sh
.work/map_genome0/nextPolish.sh] in the local_cycle.
[INFO] 2020-04-10 16:00:41,956 Throw jobID:[444371] jobCmd:[/data/users/analysis/polish/in_raw_data/in.20200410/01.lgs_polish/03.map.ref.sh
[INFO] 2020-04-10 16:00:29,948 merge_ref done
[INFO] 2020-04-10 16:00:29,949 analysis tasks done
[INFO] 2020-04-10 16:00:29,951 total jobs: 2
[INFO] 2020-04-10 16:00:29,952 Throw jobID:[444328] jobCmd:[/data/users/analysis/polish/in_raw_data/in.20200410/01.lgs_polish/02.index.ref.
sh.work/index_genome0/nextPolish.sh] in the local_cycle.
[INFO] 2020-04-10 16:00:30,455 Throw jobID:[444336] jobCmd:[/data/users/analysis/polish/in_raw_data/in.20200410/01.lgs_polish/02.index.ref.
sh.work/index_genome1/nextPolish.sh] in the local_cycle.
[INFO] 2020-04-10 16:00:41,449 index_genome done
[INFO] 2020-04-10 16:00:41,450 analysis tasks done
[INFO] 2020-04-10 16:00:41,452 total jobs: 2
[INFO] 2020-04-10 16:00:41,453 Throw jobID:[444364] jobCmd:[/data/users/analysis/polish/in_raw_data/in.20200410/01.lgs_polish/03.map.ref.sh
.work/map_genome0/nextPolish.sh] in the local_cycle.
[INFO] 2020-04-10 16:00:41,956 Throw jobID:[444371] jobCmd:[/data/users/analysis/polish/in_raw_data/in.20200410/01.lgs_polish/03.map.ref.sh
.work/map_genome1/nextPolish.sh] in the local_cycle.
[INFO] 2020-04-10 16:01:42,744 align_genome done
[INFO] 2020-04-10 16:01:42,745 analysis tasks done
[INFO] 2020-04-10 16:01:42,746 total jobs: 1
[INFO] 2020-04-10 16:01:42,748 Throw jobID:[444531] jobCmd:[/data/users/analysis/polish/in_raw_data/in.20200410/01.lgs_polish/04.merge.bam.
sh.work/merge_bam0/nextPolish.sh] in the local_cycle.
[INFO] 2020-04-10 16:01:44,823 merge_bam done
[INFO] 2020-04-10 16:01:44,830 analysis tasks done
[INFO] 2020-04-10 16:01:44,832 total jobs: 2
[INFO] 2020-04-10 16:01:44,833 Throw jobID:[444550] jobCmd:[/data/users/analysis/polish/in_raw_data/in.20200410/01.lgs_polish/05.polish.ref
.sh.work/polish_genome0/nextPolish.sh] in the local_cycle.
[INFO] 2020-04-10 16:01:45,336 Throw jobID:[444563] jobCmd:[/data/users/analysis/polish/in_raw_data/in.20200410/01.lgs_polish/05.polish.ref
.sh.work/polish_genome1/nextPolish.sh] in the local_cycle.
[INFO] 2020-04-10 16:02:09,261 polish_genome done
[INFO] 2020-04-10 16:02:09,262 step 2 and task 1 start:
[INFO] 2020-04-10 16:02:09,262 analysis tasks done
[INFO] 2020-04-10 16:02:09,263 total jobs: 1
[INFO] 2020-04-10 16:02:09,264 Throw jobID:[444598] jobCmd:[/data/users/analysis/polish/in_raw_data/in.20200410/02.score_chain/01.merge.ref.sh.work/merge_ref0/merge_ref.sh] in the local_cycle.
[INFO] 2020-04-10 16:02:10,273 merge_ref done
[INFO] 2020-04-10 16:02:10,274 analysis tasks done
[INFO] 2020-04-10 16:02:10,277 total jobs: 2
[INFO] 2020-04-10 16:02:10,278 Throw jobID:[444605] jobCmd:[/data/users/analysis/polish/in_raw_data/in.20200410/02.score_chain/02.index.ref.sh.work/index_genome0/nextPolish.sh] in the local_cycle.
[INFO] 2020-04-10 16:02:10,780 Throw jobID:[444611] jobCmd:[/data/users/analysis/polish/in_raw_data/in.20200410/02.score_chain/02.index.ref.sh.work/index_genome1/nextPolish.sh] in the local_cycle.
[INFO] 2020-04-10 16:07:47,819 index_genome done
[INFO] 2020-04-10 16:07:47,820 analysis tasks done
[INFO] 2020-04-10 16:07:47,822 total jobs: 2
[INFO] 2020-04-10 16:07:47,824 Throw jobID:[445038] jobCmd:[/data/users/analysis/polish/in_raw_data/in.20200410/02.score_chain/03.map.ref.sh.work/map_genome0/nextPolish.sh] in the local_cycle.
[INFO] 2020-04-10 16:07:48,326 Throw jobID:[445049] jobCmd:[/data/users/analysis/polish/in_raw_data/in.20200410/02.score_chain/03.map.ref.sh.work/map_genome1/nextPolish.sh] in the local_cycle.
[INFO] 2020-04-10 18:09:10,421 align_genome done
[INFO] 2020-04-10 18:09:10,422 analysis tasks done
[INFO] 2020-04-10 18:09:10,424 total jobs: 1
[INFO] 2020-04-10 18:09:10,426 Throw jobID:[5810] jobCmd:[/data/users/analysis/polish/in_raw_data/in.20200410/02.score_chain/04.merge.bam.sh.work/merge_bam0/nextPolish.sh] in the local_cycle.
[INFO] 2020-04-10 18:21:18,900 merge_bam done
[INFO] 2020-04-10 18:21:18,907 analysis tasks done
[INFO] 2020-04-10 18:21:18,909 total jobs: 2
[INFO] 2020-04-10 18:21:18,910 Throw jobID:[10332] jobCmd:[/data/users/analysis/polish/in_raw_data/in.20200410/02.score_chain/05.polish.ref.sh.work/polish_genome0/nextPolish.sh] in the local_cycle.
[INFO] 2020-04-10 18:21:20,725 Throw jobID:[10347] jobCmd:[/data/users/analysis/polish/in_raw_data/in.20200410/02.score_chain/05.polish.ref.sh.work/polish_genome1/nextPolish.sh] in the local_cycle.
[INFO] 2020-04-10 18:22:46,210 polish_genome done
[INFO] 2020-04-10 18:22:46,210 step 3 and task 2 start:
[INFO] 2020-04-10 18:22:46,211 analysis tasks done
[INFO] 2020-04-10 18:22:46,212 total jobs: 1
[INFO] 2020-04-10 18:22:46,212 Throw jobID:[10520] jobCmd:[/data/users/analysis/polish/in_raw_data/in.20200410/03.kmer_count/01.merge.ref.sh.work/merge_ref0/merge_ref.sh] in the local_cycle.
[INFO] 2020-04-10 18:22:47,222 merge_ref done
[INFO] 2020-04-10 18:22:47,223 analysis tasks done
[INFO] 2020-04-10 18:22:47,225 total jobs: 2
[INFO] 2020-04-10 18:22:47,226 Throw jobID:[10536] jobCmd:[/data/users/analysis/polish/in_raw_data/in.20200410/03.kmer_count/02.index.ref.sh.work/index_genome0/nextPolish.sh] in the local_cycle.
[INFO] 2020-04-10 18:22:47,729 Throw jobID:[10541] jobCmd:[/data/users/analysis/polish/in_raw_data/in.20200410/03.kmer_count/02.index.ref.sh.work/index_genome1/nextPolish.sh] in the local_cycle.
[INFO] 2020-04-10 18:29:10,225 index_genome done
[INFO] 2020-04-10 18:29:10,226 analysis tasks done
[INFO] 2020-04-10 18:29:10,228 total jobs: 2
[INFO] 2020-04-10 18:29:10,229 Throw jobID:[12256] jobCmd:[/data/users/analysis/polish/in_raw_data/in.20200410/03.kmer_count/03.map.ref.sh.work/map_genome0/nextPolish.sh] in the local_cycle.
[INFO] 2020-04-10 18:29:10,732 Throw jobID:[12267] jobCmd:[/data/users/analysis/polish/in_raw_data/in.20200410/03.kmer_count/03.map.ref.sh.work/map_genome1/nextPolish.sh] in the local_cycle.
[INFO] 2020-04-10 20:21:23,277 align_genome done
[INFO] 2020-04-10 20:21:23,278 analysis tasks done
[INFO] 2020-04-10 20:21:23,280 total jobs: 1
[INFO] 2020-04-10 20:21:23,281 Throw jobID:[32947] jobCmd:[/data/users/analysis/polish/in_raw_data/in.20200410/03.kmer_count/04.merge.bam.sh.work/merge_bam0/nextPolish.sh] in the local_cycle.
[INFO] 2020-04-10 20:33:32,928 merge_bam done
[INFO] 2020-04-10 20:33:32,935 analysis tasks done
[INFO] 2020-04-10 20:33:32,969 total jobs: 2
[INFO] 2020-04-10 20:33:32,970 Throw jobID:[34084] jobCmd:[/data/users/analysis/polish/in_raw_data/in.20200410/03.kmer_count/05.polish.ref.sh.work/polish_genome0/nextPolish.sh] in the local_cycle.
[INFO] 2020-04-10 20:33:33,472 Throw jobID:[34097] jobCmd:[/data/users/analysis/polish/in_raw_data/in.20200410/03.kmer_count/05.polish.ref.sh.work/polish_genome1/nextPolish.sh] in the local_cycle.
[INFO] 2020-04-10 20:36:59,994 polish_genome done
[INFO] 2020-04-10 20:36:59,995 step 4 and task 1 start:
[INFO] 2020-04-10 20:37:00,003 analysis tasks done
[INFO] 2020-04-10 20:37:00,005 total jobs: 1
[INFO] 2020-04-10 20:37:00,006 Throw jobID:[34416] jobCmd:[/data/users/analysis/polish/in_raw_data/in.20200410/04.score_chain/01.merge.ref.sh.work/merge_ref0/merge_ref.sh] in the local_cycle.
[INFO] 2020-04-10 20:37:01,013 merge_ref done
[INFO] 2020-04-10 20:37:01,013 analysis tasks done
[INFO] 2020-04-10 20:37:01,014 total jobs: 2
[INFO] 2020-04-10 20:37:01,015 Throw jobID:[34428] jobCmd:[/data/users/analysis/polish/in_raw_data/in.20200410/04.score_chain/02.index.ref.sh.work/index_genome0/nextPolish.sh] in the local_cycle.
[INFO] 2020-04-10 20:37:01,517 Throw jobID:[34434] jobCmd:[/data/users/analysis/polish/in_raw_data/in.20200410/04.score_chain/02.index.ref.sh.work/index_genome1/nextPolish.sh] in the local_cycle.
[INFO] 2020-04-10 20:42:59,891 index_genome done
[INFO] 2020-04-10 20:42:59,892 analysis tasks done
[INFO] 2020-04-10 20:42:59,894 total jobs: 2
[INFO] 2020-04-10 20:42:59,895 Throw jobID:[34995] jobCmd:[/data/users/analysis/polish/in_raw_data/in.20200410/04.score_chain/03.map.ref.sh.work/map_genome0/nextPolish.sh] in the local_cycle.
[INFO] 2020-04-10 20:43:00,398 Throw jobID:[35005] jobCmd:[/data/users/analysis/polish/in_raw_data/in.20200410/04.score_chain/03.map.ref.sh.work/map_genome1/nextPolish.sh] in the local_cycle.
[INFO] 2020-04-10 22:34:21,997 align_genome done
[INFO] 2020-04-10 22:34:21,998 analysis tasks done
[INFO] 2020-04-10 22:34:22,000 total jobs: 1
[INFO] 2020-04-10 22:34:22,001 Throw jobID:[64580] jobCmd:[/data/users/analysis/polish/in_raw_data/in.20200410/04.score_chain/04.merge.bam.sh.work/merge_bam0/nextPolish.sh] in the local_cycle.
[INFO] 2020-04-10 22:46:27,674 merge_bam done
[INFO] 2020-04-10 22:46:27,680 analysis tasks done
[INFO] 2020-04-10 22:46:27,683 total jobs: 2
[INFO] 2020-04-10 22:46:27,684 Throw jobID:[67518] jobCmd:[/data/users/analysis/polish/in_raw_data/in.20200410/04.score_chain/05.polish.ref.sh.work/polish_genome0/nextPolish.sh] in the local_cycle.
[INFO] 2020-04-10 22:46:28,186 Throw jobID:[67536] jobCmd:[/data/users/analysis/polish/in_raw_data/in.20200410/04.score_chain/05.polish.ref.sh.work/polish_genome1/nextPolish.sh] in the local_cycle.
[INFO] 2020-04-10 22:47:51,484 polish_genome done
[INFO] 2020-04-10 22:47:51,484 step 5 and task 2 start:
[INFO] 2020-04-10 22:47:51,485 analysis tasks done
[INFO] 2020-04-10 22:47:51,486 total jobs: 1
[INFO] 2020-04-10 22:47:51,486 Throw jobID:[67678] jobCmd:[/data/users/analysis/polish/in_raw_data/in.20200410/05.kmer_count/01.merge.ref.sh.work/merge_ref0/merge_ref.sh] in the local_cycle.
[INFO] 2020-04-10 22:47:52,493 merge_ref done
[INFO] 2020-04-10 22:47:52,493 analysis tasks done
[INFO] 2020-04-10 22:47:52,495 total jobs: 2
[INFO] 2020-04-10 22:47:52,495 Throw jobID:[67686] jobCmd:[/data/users/analysis/polish/in_raw_data/in.20200410/05.kmer_count/02.index.ref.sh.work/index_genome0/nextPolish.sh] in the local_cycle.
[INFO] 2020-04-10 22:47:52,998 Throw jobID:[67691] jobCmd:[/data/users/analysis/polish/in_raw_data/in.20200410/05.kmer_count/02.index.ref.sh.work/index_genome1/nextPolish.sh] in the local_cycle.
[INFO] 2020-04-10 22:53:51,846 index_genome done
[INFO] 2020-04-10 22:53:51,846 analysis tasks done
[INFO] 2020-04-10 22:53:51,848 total jobs: 2
[INFO] 2020-04-10 22:53:51,849 Throw jobID:[68378] jobCmd:[/data/users/analysis/polish/in_raw_data/in.20200410/05.kmer_count/03.map.ref.sh.work/map_genome0/nextPolish.sh] in the local_cycle.
[INFO] 2020-04-10 22:53:52,351 Throw jobID:[68388] jobCmd:[/data/users/analysis/polish/in_raw_data/in.20200410/05.kmer_count/03.map.ref.sh.work/map_genome1/nextPolish.sh] in the local_cycle.
[INFO] 2020-04-11 00:43:12,225 align_genome done
[INFO] 2020-04-11 00:43:12,252 analysis tasks done
[INFO] 2020-04-11 00:43:12,253 total jobs: 1
[INFO] 2020-04-11 00:43:12,254 Throw jobID:[84537] jobCmd:[/data/users/analysis/polish/in_raw_data/in.20200410/05.kmer_count/04.merge.bam.sh.work/merge_bam0/nextPolish.sh] in the local_cycle.
[INFO] 2020-04-11 00:55:20,790 merge_bam done
[INFO] 2020-04-11 00:55:20,797 analysis tasks done
[INFO] 2020-04-11 00:55:20,798 total jobs: 2
[INFO] 2020-04-11 00:55:20,798 Throw jobID:[85579] jobCmd:[/data/users/analysis/polish/in_raw_data/in.20200410/05.kmer_count/05.polish.ref.sh.work/polish_genome0/nextPolish.sh] in the local_cycle.
[INFO] 2020-04-11 00:55:21,300 Throw jobID:[85593] jobCmd:[/data/users/analysis/polish/in_raw_data/in.20200410/05.kmer_count/05.polish.ref.sh.work/polish_genome1/nextPolish.sh] in the local_cycle.
[INFO] 2020-04-11 00:58:47,354 polish_genome done
[INFO] 2020-04-11 00:58:47,355 nextPolish has finished, and final polished genome files:
[INFO] 2020-04-11 00:58:47,355 ESC[35m /data/users/analysis/polish/in_raw_data/./in.20200410/05.kmer_count/*polish.ref.sh.work/polish_genome*/genome.nextpolish.part*.fasta ESC[0m

**Comment by moold** [comment]
As the log shows, the final polished files are `/data/users/analysis/polish/in_raw_data/./in.20200410/05.kmer_count/polish.ref.sh.work/polish_genome/genome.nextpolish.part*.fasta`,  the file `genome.nextpolish.part001.fasta` is only one of result files. You can use `ls -l /data/users/analysis/polish/in_raw_data/./in.20200410/05.kmer_count/polish.ref.sh.work/polish_genome/genome.nextpolish.part*.fasta` to check.

**Comment by SYSU-SinLee** [comment]
> As the log shows, the final polished files are `/data/users/analysis/polish/in_raw_data/./in.20200410/05.kmer_count/polish.ref.sh.work/polish_genome/genome.nextpolish.part*.fasta`, the file `genome.nextpolish.part001.fasta` is only one of result files. You can use `ls -l /data/users/analysis/polish/in_raw_data/./in.20200410/05.kmer_count/polish.ref.sh.work/polish_genome/genome.nextpolish.part*.fasta` to check.

I just realized that the polished genome was divided under two paths named "polish_genome0/genome.nextpolish.part0.fasta" and "polish_genome1/genome.nextpolish.part1.fasta" respectively. That's different from the log file.  Thanks for your time. 
PS: I guess this might be confusing to some others.
