### ISSUE TITLE
long-read only polishing error: Error, task only accept: [all,1,2,3,4]

### ISSUE THREAD

**Issue by gitcruz** [Nextomics/NextPolish#22]
Hi,
I am trying to polish an assembly with NextPolish version 1.0.3 on a single-node with 24 cores. I am using just canu error corrected reads. As we do not have illumina short reads and sgs_option seems mandatory, i just passed an empty.fofn

This is the config file I provided with the intention of running 5 polishing iterations:

[General]
job_type = local
job_prefix = pacbio-polish-5-assembly
task = 55555
rewrite = yes
rerun = 2
parallel_jobs = 1
multithread_jobs = 24
genome = ./assembly.fa
genome_size = auto
workdir = ./polished_out
polish_options = -p {multithread_jobs}

[sgs_option]
sgs_fofn = ./assembly-illumina.fofn
sgs_options = -max_depth 100

[lgs_option]
lgs_fofn = ./assembly-pacbio-corr.fofn
lgs_options = -min_read_len 10k -max_read_len 150k -max_depth 60
lgs_minimap2_options = -x map-pb -t 6

I am getting this error after a minute:
[INFO] 2020-05-15 18:07:40,902 start...
[INFO] 2020-05-15 18:07:40,903 logfile: pid19519.log.info
[WARNING] 2020-05-15 18:07:40,922 Re-write workdir
[INFO] 2020-05-15 18:07:45,632 scheduled tasks:
[5, 5, 5, 5, 5]
[INFO] 2020-05-15 18:07:45,632 options:
[INFO] 2020-05-15 18:07:45,633 {'polish_options': '-p 24', 'rewrite': 1, 'job_prefix': 'pacbio-polish-5-assembly', 'job_type': 'local', 'cluster_options': '', 's\
np_valid': '/home/devel/my_genome__NextPolish_v1.0.3_long_reads_5_iterations/./polished_out/%02d.snp_valid', 'kmer_count': '/home/devel/my_genome__NextPolish_v1.\
0.3_long_reads_5_iterations/./polished_out/%02d.kmer_count', 'lgs_fofn': '/home/devel/my_genome__NextPolish_v1.0.3_long_reads_5_iterations/./assembly-pacbio-corr\
.fofn', 'sgs_max_depth': '100', 'sgs_block_size': 500000000, 'lgs_max_read_len': '150k', 'parallel_jobs': '1', 'multithread_jobs': '24', 'snp_phase': '/home/deve\
l/my_genome__NextPolish_v1.0.3_long_reads_5_iterations/./polished_out/%02d.snp_phase', 'genome': '/home/devel/my_genome__NextPolish_v1.0.3_long_reads_5_iteration\
s/./assembly.fa', 'genome_size': 2464389961L, 'workdir': '/home/devel/my_genome__NextPolish_v1.0.3_long_reads_5_iterations/./polished_out', 'cleantmp': 0, 'sgs_a\
lign_options': 'minimap2 -a -x sr -t 24', 'sgs_unpaired': '0', 'sgs_fofn': '/home/devel/my_genome__NextPolish_v1.0.3_long_reads_5_iterations/./assembly-illumina.\
fofn', 'align_threads': 24, 'sgs_use_duplicate_reads': 0, 'score_chain': '/home/devel/my_genome__NextPolish_v1.0.3_long_reads_5_iterations/./polished_out/%02d.sc\
ore_chain', 'task': [5, 5, 5, 5, 5], 'lgs_max_depth': '60', 'lgs_block_size': 500000000, 'lgs_minimap2_options': '-x map-pb -t 6', 'rerun': 2, 'lgs_min_read_len'\
: '1k'}
[INFO] 2020-05-15 18:07:45,633 step 0 and task 5 start:
[ERROR] 2020-05-15 18:07:45,633 Error, task only accept: [all,1,2,3,4]

Is it possible to polish just with the pacbio data? am I doing something wrong? 

Thanks,
F.

**Comment by moold** [comment]
Yes, but you should update to the latest version.
