### ISSUE TITLE
Question on NextPolish output

### ISSUE THREAD

**Issue by Ural-Yunusbaev** [Nextomics/NextPolish#23]
Hi, Dr. Hu, thanks for your awesome polisher. I have a question NextPolish output: 
I found that NextPolish generates two output files. In my case it looks like this:
genome.nextpolish.part000.fasta
genome.nextpolish.part001.fasta
Why did my contigs split into two files? What does it mean? Is there any reason important for downstream analysis? What are the criteria for this split?
My output details:
wc  ~/NextPolish/Acer_data/./01_rundir/02.kmer_count/*polish.ref.sh.work/polish_genome*/genome.nextpolish.part*.fasta
       72       108 124308796 /home/crciv/AcerChrAssemb/NextPolish/Acer_data/./01_rundir/02.kmer_count/05.polish.ref.sh.work/polish_genome0/genome.nextpolish.part000.fasta
       56        84  99657733 ~/NextPolish/Acer_data/./01_rundir/02.kmer_count/05.polish.ref.sh.work/polish_genome1/genome.nextpolish.part001.fasta
      128       192 223966529 total
wc ~/NextPolish/Acer_data/01_rundir/02.kmer_count/05.polish.ref.sh.work/genome.nextpolish.part000_part001.fasta
      128       192 223966529 ~/NextPolish/Acer_data/01_rundir/02.kmer_count/05.polish.ref.sh.work/genome.nextpolish.part000_part001.fasta

Thanks in advance!
Ural Yunusbaev.

**Comment by moold** [comment]
Hi, just for parallel computation, you can merge/cat them to one file. You can see [here](https://github.com/Nextomics/NextPolish/blob/master/doc/bwa.sh) to avoid it.

**Comment by moold** [comment]
If you run on a cluster, such as SGE, PBS. The`parallel_jobs` option us used to determine how many subfile to split, so NextPolish can submit one subfile to one compute node.

**Comment by Ural-Yunusbaev** [comment]
Thanks!
