### ISSUE TITLE
BUG for task=best

### ISSUE THREAD

**Issue by zhk2017** [Nextomics/NextPolish#24]
In the example, when set task = best, "551212" will be used:
 **_task = best              # task need to run [all, default, best, 1, 2, 5, 12, 1212...], all=[5]1234, default=[5]12, best=[55]1212. (default: default)_**

But in the script lib/configParser.py download from https://github.com/Nextomics/NextPolish/releases/download/v1.0.3/NextPolish-CentOS6.9.tgz

def _settask(self):
        import re
        task = re.sub(r'[\s,;]+','', self.cfg['task'])
        if task == 'all':
            task = '1234'
        elif task == 'default':
            task = '12'
        elif task == 'best':                                                                                                                   
            **### task = '12121212'**
when tast=best, use 12121212, it's a bug?

Haikuan

**Comment by moold** [comment]
Hi,
you should update to the latest version and the documentation is updated with the new version.

**Comment by zhk2017** [comment]
> Hi,
> you should update to the latest version and the documentation is updated with the new version.

Thx, the problem was fixed.
