### ISSUE TITLE
nextPolish: command not found...

### ISSUE THREAD

**Issue by yanzhongsino** [Nextomics/NextPolish#25]
Hi, while I follow the workflow to install NextPolish, I met an error "nextPolish: command not found" in the step of testing nextPolish after "make".
After the command "cd ./NextPolish && make", I didn't get success message of finishing installation but get the information "make[2]: Leaving directory `/data/users/yurx/yanzhong/software/NextPolish/util/minimap2'
make[1]: Leaving directory `/data/users/yurx/yanzhong/software/NextPolish/util'" in the end and then finish the installation.
Then, I try to test the running of nextPolish in the directory of "NextPolish" using the command "nextPolish ./test_data/run.cfg", I get the message "nextPolish: command not found". I try to use "chmod 777 nextPolish" but it didn't work.
I will appreciate any help.

**Comment by moold** [comment]
try this `./nextPolish ./test_data/run.cfg` or add `nextPolish` to your environment variables.
