### ISSUE TITLE
NextPolish was core dumped in ‘01.lgs_polish/05.polish.ref.sh.work’

### ISSUE THREAD

**Issue by jinhao94** [Nextomics/NextPolish#26]
When I run nextPolish， the job stoped at 01.lgs_polish/05.polish.ref.sh.work， but there were no error log in nextPolish.sh.e. The python script named NextPolish/lib/nextpolish2.py did not use the CPU. And the jobs has been running for a long time（more than 1 day）at this step.

The directory structure of 05.polish.ref.sh.work was：
polish_genome0
├── [ 49M]  genome.nextpolish.part000.fasta
├── [ 787]  nextPolish.sh
├── [   0]  nextPolish.sh.done
├── [ 46K]  nextPolish.sh.e
└── [   6]  nextPolish.sh.o
polish_genome1
├── [2.7G]  core.336510
├── [ 47M]  genome.nextpolish.part001.fasta
├── [ 787]  nextPolish.sh
├── [ 43K]  nextPolish.sh.e
└── [   6]  nextPolish.sh.o
polish_genome2
├── [ 49M]  genome.nextpolish.part002.fasta
├── [ 787]  nextPolish.sh
├── [   0]  nextPolish.sh.done
├── [ 52K]  nextPolish.sh.e
└── [   6]  nextPolish.sh.o

The 3 lines at _the end of nextPolish.sh.e_ as follow:
gap_aln:194 sup_aln:206 depth_cluster:2 gap_cluster:0 bin_len:500 median_depth:63
gap_aln:274 sup_aln:330 depth_cluster:2 gap_cluster:0 bin_len:500 median_depth:142
[INFO] 2020-06-08 23:17:04,873 Start a corrected worker in 336888 from parent 336295

nextPolish v1.2.1

My run.cfg file:
[General]
job_type = local
job_prefix = nextPolish
task = 55551212
rewrite = yes
rerun = 3
parallel_jobs = 3
multithread_jobs = 20
genome = ./A72_assembly.fasta
genome_size = auto
workdir = ./
polish_options = -p {multithread_jobs}

[sgs_option]
sgs_fofn = ./sgc.config
sgs_options = -max_depth 100

[lgs_option]
lgs_fofn = ./lgc.config
lgs_options = -min_read_len 1k -max_read_len 150k -max_depth 100
lgs_minimap2_options = -x map-ont

[polish_options]
ploidy=1

**Comment by moold** [comment]
Hi, could you compare the result file `05.polish.ref.sh.work/polish_genome*/genome.nextpolish.part*.fasta` and its input file `input.genome.fasta` to extract the un-polished sequence and its bam `lgs.sort.bam` using `samtools view -b lgs.sort.bam $UN-POLISHED-SEQUENCE-NAME` and send this data to me, so I can debug it, Thank you so much.

**Comment by jinhao94** [comment]
Thank you for your help. I uoload the data into 百度云.
链接：https://pan.baidu.com/s/1J9CFwBjqnX_utywjbTXnGA 
提取码：lzt1

If you need more information,   you can email me at jinhao94@126.com.

**Comment by jinhao94** [comment]
I reassembled the data using `Flye v2.7.1`, and everything goes well. Thank you again!

**Comment by moold** [comment]
Hi, actually, I have successfully run your data without any errors with nextPolish v1.2.1. While I found the length of your input genome is too short, it does not look like contigs but some reads. It may not be appropriate to use NextPolish to do the polish, instend, using NextDenovo or other similar tools to do the self-corrections may be better.

**Comment by jinhao94** [comment]
Thank you for your help! This data is a human gut metagenomic data. I found `Flye v2.7.1` is the most suitable software. As per your recommendation, I will remove the sequences with length less than 2000 bp.
