### ISSUE TITLE
I got a simple question to ask :)

### ISSUE THREAD

**Issue by Zea1nfO** [Nextomics/NextPolish#27]
Hi guys
i just started to do some genome assembly jobs. So i got some confusion about the data type.

in the readme, should the long reads used to polish the genome be the corrected reads after i use nextdenovo to correct?

and should the short reads be the illumina seq?

Do i understand it right?

Thanks a lot!

**Comment by moold** [comment]
Hi, the long reads should be the raw long reads (PacBio or NanoPore), not corrected reads, because  the corrected reads may contain some system errors (induced by correction step), the short reads are the illumina seq data.

**Comment by Zea1nfO** [comment]
> Hi, the long reads should be the raw long reads (PacBio or NanoPore), not corrected reads, because the corrected reads may contain some system errors (induced by correction step), the short reads are the illumina seq data.

Thanks a lot , i got it.

As described in the readme, i think i should use raw long reads to polish genome ,and then use the short reads.
both of them can do with nextpolish, but they need different config  file.
besides, if i run short reads polish step, i can do as the step in this [scripts](https://github.com/Nextomics/NextPolish/blob/master/doc/bwa.sh)  to custom the parameter.
Am i right?

**Comment by moold** [comment]
Hi, just one config file, but set task start with "5" and lgs_fofn. such as `task=551212`, see `test_data/run.cfg`

**Comment by Zea1nfO** [comment]
> Hi, just one config file, but set task start with "5" and lgs_fofn. such as `task=551212`, see `test_data/run.cfg`

Thanks a lot for you patient reply.
i will try it.
:)
