### ISSUE TITLE
Getting error when running lib/nextpolish1.py using python3

### ISSUE THREAD

**Issue by J-Wall** [Nextomics/NextPolish#28]
Hi there, I am trying to run NextPolish using a some previously-created alignments, basically following your [example](https://github.com/Nextomics/NextPolish/blob/master/doc/bwa.sh), but I am getting an error if I run it with python3. Seems to work with python2 though.

Here is the traceback:

```
Traceback (most recent call last):
  File "/home/jesse/software/NextPolish/lib/nextpolish1.py", line 334, in <module>
    main(args)
  File "/home/jesse/software/NextPolish/lib/nextpolish1.py", line 229, in main
    print(seq_name + ' %d %d %c %c' % pbase, file=sys.stderr)
TypeError: %c requires int or char
```

**Comment by moold** [comment]
Thank you for your feedback, and I will fix it in the next release. But now, you can change line 187 in file nextpolish1.py to `pbases = [(pdata[p].pos, pdata[p].index, byte2str(pdata[p].curbase), byte2str(pdata[p].base)) for p in range(c_seq.contents.datalength)]` or use python2.

**Comment by moold** [comment]
Hi, I have updated a new version to fix this bug, pls update to the lastest version to avoid this bug.
