### ISSUE TITLE
Errors or waining?

### ISSUE THREAD

**Issue by wangzhennan14** [Nextomics/NextPolish#3]
Hi,
    When I used NextPolish, there wai some errors, what is the matter?
    
![samtool](https://user-images.githubusercontent.com/17285718/62264809-12f7e800-b454-11e9-8063-d0665ec44a17.PNG)
![捕获](https://user-images.githubusercontent.com/17285718/62264817-1c815000-b454-11e9-9f45-0a5b4c320821.PNG)

     Could you give me some advice to solve it? Thank you!
Wang

**Comment by moold** [comment]
Could you check whether this file  `dbg.raw.fa2.fai` is existed? From your log, it seems this file is not existed.

**Comment by moold** [comment]
I will close this issue, but if you still have this problem, feel free to reopen it.
