### ISSUE TITLE
I think there is some bug within nextpolish2.py

### ISSUE THREAD

**Issue by Zea1nfO** [Nextomics/NextPolish#30]
Hi sir,

Recently i use nextdenovo to get the draft genome, so i decide to polish my genome with nextpolish.
I set the "task=551212 ", "polish_options = -p 30 "and "parallel_jobs = 3" in run.cfg.
When the nextPolish went to polish.ref.sh.work of 00.lgs_polish step.
I just find the each nextpolish2.py jobs is using almost 100 threads at the beginnning of the process.
I have to stop it and do it one by one. 
After this , i continue the whole polish jobs by taping the command "nextPolish run.cfg".
And the problem rose again when the nextPolish went to polish.ref.sh.work of 01.lgs_polish step.
i open the nextpolish.sh and i find the -p option is set as 30.
So i think maybe this is a bug in nextpolish2.py.
Maybe it its because my genome is huge, which is about 2 Gb?
Besides, i just download the version 1.2.3, and the same consequence show again

Hoping for your reply, thanks.

**Comment by moold** [comment]
Hi, this is not a bug, you can check the log file in  01.lgs_polish/0*.polish.ref.sh.work/polish_genome*/nextPolish.sh.e, it shows you can use `-a` option to disable automatically adjust window size (-w) and processes (-p).

**Comment by Zea1nfO** [comment]
> Hi, this is not a bug, you can check the log file in 01.lgs_polish/0*.polish.ref.sh.work/polish_genome*/nextPolish.sh.e, it shows you can use `-a` option to disable automatically adjust window size (-w) and processes (-p).

Sorry about that, i will check the log file.

Beside, can i do the lgs and sgs polish separately?
Just like this:
I create a cfg with task = "55".
Then i use the lgs polish result to do sgs polish with a cfg whose task is set as "1212".
Can i do this in this way?

**Comment by moold** [comment]
yes

**Comment by Zea1nfO** [comment]
> yes
Thanks a lot 
:)
