### ISSUE TITLE
nextpolish1.py generate the sequence with wrong id

### ISSUE THREAD

**Issue by Zea1nfO** [Nextomics/NextPolish#31]
Hi sir
I try the newest nextpolish, and i found the nextpolish1.py generate the genome file whose all seq is named "_np1".
I check the test_data result, the same problem is in there as well.
The problem make the samtools cannot index the file correctly, so we can`t get right blc file as well.
This problem will not stop the whole process, but will generate a one seq file in final.
The previous version is good at that.

Is there some way to solve this in the newset version？

Waiting for your reply.
Thanks a lot.

**Comment by moold** [comment]
sorry about that, I will fix it and release a new version in a few minutes.

**Comment by Zea1nfO** [comment]
> sorry about that, I will fix it and release a new version in a few minutes.

Thanks a lot
:)
