### ISSUE TITLE
error when run test data

### ISSUE THREAD

**Issue by binlu1981** [Nextomics/NextPolish#33]
Hi, 
There is an error when run test data.
[ERROR] 2020-06-30 09:43:36,569 polish_genome failed: please check the following logs:
[ERROR] 2020-06-30 09:43:36,570 /NextPolish/test_data/01_rundir/00.lgs_polish/04.polish.ref.sh.work/polish_genome0/nextPolish.sh.e

the tail of the log:
Command terminated by signal 11
0.03user 0.00system 0:00.24elapsed 18%CPU (0avgtext+0avgdata 10812maxresident)k
0inputs+0outputs (0major+1743minor)pagefaults 0swaps

The nextPolish version is v1.2.4. The system is ubuntu 18.04.

Any suggestions?

**Comment by moold** [comment]
Could you paste all content of the log file to here?

**Comment by binlu1981** [comment]
[INFO] 2020-06-30 16:12:03,359 start...
[INFO] 2020-06-30 16:12:03,360 logfile: pid26765.log.info
[WARNING] 2020-06-30 16:12:03,361 Re-write workdir
[INFO] 2020-06-30 16:12:03,365 scheduled tasks:
[5, 1, 2]
[INFO] 2020-06-30 16:12:03,365 options:
[INFO] 2020-06-30 16:12:03,365 {'job_type': 'local', 'job_prefix': 'nextPolish', 'task': [5, 1, 2], 'rewrite': 1, 'cleantmp': 0, 'rerun': 3, 'parallel_jobs': '2', 'multithread_jobs': '3', 'cluster_options': '', 'genome_size': 111129, 'workdir': '/home/biosoft/NextPolish/test_data/./01_rundir', 'polish_options': '-p 3', 'sgs_use_duplicate_reads': 0, 'sgs_unpaired': '0', 'sgs_max_depth': '100', 'sgs_block_size': 5556450.0, 'sgs_align_options': 'bwa mem -p  -t 3', 'lgs_block_size': 3333870.0, 'lgs_min_read_len': '1k', 'lgs_max_read_len': '150k', 'lgs_max_depth': '60', 'lgs_minimap2_options': '-x map-ont -t 3', 'genome': '/home/biosoft/NextPolish/test_data/./raw.genome.fasta', 'sgs_fofn': '/home/biosoft/NextPolish/test_data/./sgs.fofn', 'lgs_fofn': '/home/biosoft/NextPolish/test_data/./lgs.fofn', 'lgs_polish': '/home/biosoft/NextPolish/test_data/./01_rundir/%02d.lgs_polish', 'score_chain': '/home/biosoft/NextPolish/test_data/./01_rundir/%02d.score_chain', 'kmer_count': '/home/biosoft/NextPolish/test_data/./01_rundir/%02d.kmer_count', 'snp_phase': '/home/biosoft/NextPolish/test_data/./01_rundir/%02d.snp_phase', 'snp_valid': '/home/biosoft/NextPolish/test_data/./01_rundir/%02d.snp_valid', 'align_threads': 3}
[INFO] 2020-06-30 16:12:03,365 step 0 and task 5 start:
[INFO] 2020-06-30 16:12:03,366 analysis tasks done
[INFO] 2020-06-30 16:12:03,367 total jobs: 4
[INFO] 2020-06-30 16:12:03,369 Throw jobID:[26766] jobCmd:[/home/biosoft/NextPolish/test_data/01_rundir/00.lgs_polish/01.db_split.sh.work/db_split0/nextPolish.sh] in the local_cycle.
[INFO] 2020-06-30 16:12:03,871 Throw jobID:[26775] jobCmd:[/home/biosoft/NextPolish/test_data/01_rundir/00.lgs_polish/01.db_split.sh.work/db_split1/nextPolish.sh] in the local_cycle.
[INFO] 2020-06-30 16:12:05,501 Throw jobID:[26785] jobCmd:[/home/biosoft/NextPolish/test_data/01_rundir/00.lgs_polish/01.db_split.sh.work/db_split2/nextPolish.sh] in the local_cycle.
[INFO] 2020-06-30 16:12:06,040 Throw jobID:[26798] jobCmd:[/home/biosoft/NextPolish/test_data/01_rundir/00.lgs_polish/01.db_split.sh.work/db_split3/nextPolish.sh] in the local_cycle.
[INFO] 2020-06-30 16:12:07,060 db_split done
[INFO] 2020-06-30 16:12:07,061 analysis tasks done
[INFO] 2020-06-30 16:12:07,062 total jobs: 2
[INFO] 2020-06-30 16:12:07,064 Throw jobID:[26808] jobCmd:[/home/biosoft/NextPolish/test_data/01_rundir/00.lgs_polish/02.map.ref.sh.work/map_genome0/nextPolish.sh] in the local_cycle.
[INFO] 2020-06-30 16:12:07,567 Throw jobID:[26821] jobCmd:[/home/biosoft/NextPolish/test_data/01_rundir/00.lgs_polish/02.map.ref.sh.work/map_genome1/nextPolish.sh] in the local_cycle.
[INFO] 2020-06-30 16:12:09,441 align_genome done
[INFO] 2020-06-30 16:12:09,443 analysis tasks done
[INFO] 2020-06-30 16:12:09,444 total jobs: 1
[INFO] 2020-06-30 16:12:09,445 Throw jobID:[26876] jobCmd:[/home/biosoft/NextPolish/test_data/01_rundir/00.lgs_polish/03.merge.bam.sh.work/merge_bam0/nextPolish.sh] in the local_cycle.
[INFO] 2020-06-30 16:12:10,920 merge_bam done
[INFO] 2020-06-30 16:12:10,922 analysis tasks done
[INFO] 2020-06-30 16:12:10,923 total jobs: 2
[INFO] 2020-06-30 16:12:10,925 Throw jobID:[26893] jobCmd:[/home/biosoft/NextPolish/test_data/01_rundir/00.lgs_polish/04.polish.ref.sh.work/polish_genome0/nextPolish.sh] in the local_cycle.
[INFO] 2020-06-30 16:12:11,428 Throw jobID:[26900] jobCmd:[/home/biosoft/NextPolish/test_data/01_rundir/00.lgs_polish/04.polish.ref.sh.work/polish_genome1/nextPolish.sh] in the local_cycle.
[ERROR] 2020-06-30 16:12:12,432 polish_genome failed: please check the following logs:
[ERROR] 2020-06-30 16:12:12,432 /home/biosoft/NextPolish/test_data/01_rundir/00.lgs_polish/04.polish.ref.sh.work/polish_genome0/nextPolish.sh.e
[ERROR] 2020-06-30 16:12:12,432 /home/biosoft/NextPolish/test_data/01_rundir/00.lgs_polish/04.polish.ref.sh.work/polish_genome1/nextPolish.sh.e



cat /home/biosoft/NextPolish/test_data/01_rundir/00.lgs_polish/04.polish.ref.sh.work/polish_genome0/nextPolish.sh.e
hostname
+ hostname
cd /home/biosoft/NextPolish/test_data/01_rundir/00.lgs_polish/04.polish.ref.sh.work/polish_genome0
+ cd /home/biosoft/NextPolish/test_data/01_rundir/00.lgs_polish/04.polish.ref.sh.work/polish_genome0
time /home/lvbin/anaconda3/bin/python /home/biosoft/NextPolish/lib/nextpolish2.py -s -p 3 -g /home/biosoft/NextPolish/test_data/./01_rundir/00.lgs_polish/input.genome.fasta -b /home/biosoft/NextPolish/test_data/./01_rundir/00.lgs_polish/input.genome.fasta.blc -i 0 -l /home/biosoft/NextPolish/test_data/./01_rundir/00.lgs_polish/lgs.sort.bam.list -r ont -o genome.nextpolish.part000.fasta
+ time /home/lvbin/anaconda3/bin/python /home/biosoft/NextPolish/lib/nextpolish2.py -s -p 3 -g /home/biosoft/NextPolish/test_data/./01_rundir/00.lgs_polish/input.genome.fasta -b /home/biosoft/NextPolish/test_data/./01_rundir/00.lgs_polish/input.genome.fasta.blc -i 0 -l /home/biosoft/NextPolish/test_data/./01_rundir/00.lgs_polish/lgs.sort.bam.list -r ont -o genome.nextpolish.part000.fasta
[INFO] 2020-06-30 16:12:11,006 Corrected step options:
[INFO] 2020-06-30 16:12:11,006 Namespace(alignment_identity_ratio=0.8, alignment_score_ratio=0.8, auto=True, bam_list='/home/biosoft/NextPolish/test_data/./01_rundir/00.lgs_polish/lgs.sort.bam.list', block='/home/biosoft/NextPolish/test_data/./01_rundir/00.lgs_polish/input.genome.fasta.blc', block_index='0', genome='/home/biosoft/NextPolish/test_data/./01_rundir/00.lgs_polish/input.genome.fasta', out='genome.nextpolish.part000.fasta', process=3, read_type=1, split=0, window=5000000)
Command terminated by signal 11
0.05user 0.01system 0:00.27elapsed 28%CPU (0avgtext+0avgdata 13400maxresident)k
0inputs+0outputs (0major+1919minor)pagefaults 0swaps

**Comment by moold** [comment]
Can you manually run this shell /home/biosoft/NextPolish/test_data/01_rundir/00.lgs_polish/04.polish.ref.sh.work/polish_genome0/nextPolish.sh and check if this error occurs again?

Because there is no any error info. so I can not debug it.

**Comment by binlu1981** [comment]
OK. 

[INFO] 2020-06-30 20:35:25,653 Corrected step options:
[INFO] 2020-06-30 20:35:25,653 Namespace(alignment_identity_ratio=0.8, alignment_score_ratio=0.8, auto=True, bam_list='/home/biosoft/NextPolish/test_data/./01_rundir/00.lgs_polish/lgs.sort.bam.list', block='/home/biosoft/NextPolish/test_data/./01_rundir/00.lgs_polish/input.genome.fasta.blc', block_index='0', genome='/home/biosoft/NextPolish/test_data/./01_rundir/00.lgs_polish/input.genome.fasta', out='genome.nextpolish.part000.fasta', process=3, read_type=1, split=0, window=5000000)
./nextPolish.sh: line 5: 31563 Segmentation fault      (core dumped) /home/anaconda3/bin/python /home/biosoft/NextPolish/lib/nextpolish2.py -s -p 3 -g /home/biosoft/NextPolish/test_data/./01_rundir/00.lgs_polish/input.genome.fasta -b /home/biosoft/NextPolish/test_data/./01_rundir/00.lgs_polish/input.genome.fasta.blc -i 0 -l /home/biosoft/NextPolish/test_data/./01_rundir/00.lgs_polish/lgs.sort.bam.list -r ont -o genome.nextpolish.part000.fasta

real    0m0.261s
user    0m0.058s
sys     0m0.016s

**Comment by moold** [comment]
Hi, I have tested NextPolish on an Ubuntu system, and it finished without any error. so I need more details to reproduce this error.
Could you run `ldd lib/nextpolish1.so` and `ldd lib/nextpolish2.so` ? and what's your gcc version?

**Comment by binlu1981** [comment]
`ldd lib/nextpolish1.so`
        linux-vdso.so.1 (0x00007fffe2bc6000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fcb86b40000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fcb867a2000)
        libbz2.so.1 => /lib/x86_64-linux-gnu/libbz2.so.1 (0x00007fcb86592000)
        liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007fcb8636c000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fcb8614f000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fcb85d5e000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fcb86fed000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fcb85b5a000)

 `ldd lib/nextpolish2.so`
        linux-vdso.so.1 (0x00007ffea43c2000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fe0c7e7b000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fe0c7add000)
        libbz2.so.1 => /lib/x86_64-linux-gnu/libbz2.so.1 (0x00007fe0c78cd000)
        liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007fe0c76a7000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fe0c748a000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fe0c7099000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fe0c833e000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fe0c6e95000)

gcc version is 7.5.0

**Comment by moold** [comment]
It seems everything is ok, I need more time do debug it.

**Comment by binlu1981** [comment]
Is there is a pre-compiled version? It can avoid many unnecessary installation problems.

**Comment by moold** [comment]
Hi, please download [nextpolish2.zip](https://github.com/Nextomics/NextPolish/files/4861752/nextpolish2.zip), then decompress and replace file `lib/nextpolish2.so` with it.

**Comment by binlu1981** [comment]
Work well now. Thanks. Will it be released an improved version for public?

Type           Length (bp)            Count (#)
N10                60501                   1
N20                60501                   1
N30                60501                   1
N40                60501                   1
N50                60501                   1
N60                51040                   2
N70                51040                   2
N80                51040                   2
N90                51040                   2

Min.               51040                   -
Max.               60501                   -
Ave.               55770                   -
Total             111541                   2

**Comment by moold** [comment]
Yes, I will release it in the next version.
