### ISSUE TITLE
About running time

### ISSUE THREAD

**Issue by awesomedeer** [Nextomics/NextPolish#35]
Hi!
Is it normal that **samtools** is sleeping and using less memory and threads?
Because when I check the status, it shows like below:
`PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND `
`167899 song    20   0 9892424 4.793g    968 S   0.3  5.2  42:06.05 samtools`

I am using 1.2.4.

**Comment by moold** [comment]
I am not sure, but you can use your own alignment pipeline, see [here](https://github.com/Nextomics/NextPolish/blob/master/doc/bwa.sh)

**Comment by awesomedeer** [comment]
Thanks for replying. I will have a try and give you feedback.

**Comment by awesomedeer** [comment]
It works perfect as you suggested. Thanks a lot!
