### ISSUE TITLE
PBS

### ISSUE THREAD

**Issue by JJiTT** [Nextomics/NextPolish#36]

**Comment by JJiTT** [comment]
Hi,
I invoke nextpolish with 'job_type=pbs', but get an error: "drmaa.errors.InternalException: code 1: Please set the environment variable SGE_ROOT". So, how can I set 'SGE_ROOT' in PBS/Torque ? thanks a lot.

**Comment by moold** [comment]
see [https://github.com/moold/ParallelTask](https://github.com/moold/ParallelTask)

**Comment by JJiTT** [comment]
thanks, that's the answer what I want.
