### ISSUE TITLE
will it be OK to use HIFI reads to consensus the genome ?

### ISSUE THREAD

**Issue by longzhangnation** [Nextomics/NextPolish#37]
Hi，
  I have a genome generated with nanopore read , and I want to consensus it with Pacbio reads , will it be OK ? In addtion , how many iterations will be best to consensus or polish the genome because my assembly is large ?

**Comment by moold** [comment]
For pacbio CLR data, set `lgs_minimap2_options = -x map-pb` is ok, for HiFi data, I do not test.

**Comment by longzhangnation** [comment]
Thanks for your quick reply . I will give a try .
