### ISSUE TITLE
qustion about the times of iteration using long reads for consensus?

### ISSUE THREAD

**Issue by longzhangnation** [Nextomics/NextPolish#40]
Hi,
  I am using the Nextpolish for my genome consensusing using PacBio long reads , But the genome is very large to 8G,  so it will take very long time to consensus the genome if I consensus it for several time , do you have any test for the iteration to get a satisfying  result ? I see the iterations for SGS data on the github ,but not see the recommended times for long reads .

**Comment by moold** [comment]
I don't test. But, in general, the accuracy of an assembly depends on polishing with short reads, so 2-3 round polishing with long reads is enough for an assembly with corrected reads.
