### ISSUE TITLE
Some confusion about the seq_split and the paried fasta file

### ISSUE THREAD

**Issue by Zea1nfO** [Nextomics/NextPolish#42]
Hi sir,

I use seqkit to filt out the sequence that contain "N" in my short reads file.

But i ignore the "paired" issue at the first.

I just use the filtered-not-totally-paired short reads to polish my genome.

The seq_split is working fine with the filtered-not-totally-paired short reads.

There is no bug info during the whole analysis.

But i am not sure that whether this kind of file can generate the right polished genome.

Do i need to filter out the unpaired reads after i filter out the containing "N" reads to get the good-paired NGS_1.fq and NGS_2.fq ?

Thanks a lot.

**Comment by moold** [comment]
Yes, you should filter out the unpaired reads. `seq_split` dose not check whether your input files are legal  if you set `paired` option.

**Comment by Zea1nfO** [comment]
> Yes, you should filter out the unpaired reads. `seq_split` dose not check whether your input files are legal if you set `paired` option.

Thanks a lot
Have a nice day : )
