### ISSUE TITLE
What is a proper "-min_read_len" options?

### ISSUE THREAD

**Issue by Zea1nfO** [Nextomics/NextPolish#45]
Hi sir, sorry to bother you again.

I use nextDenovo to assembly my genome, and the recommanded seed_cutoff is about 30k generated by seq_stat with "-d 45".
And a i got pretty good assembly result with long N50.
Then i wanna use nextpolish to polish my draft genome with my ONT and Illumina reads.
When i started to set to config of nextpolish, a little confusion came out.
I see the "-min_read_len" in [here](https://github.com/Nextomics/NextPolish/blob/master/doc/run.cfg) is 10k but the default is 1k.
So how can i set a proper one, or maybe i should use seq_stat to get a "-min_read_len" due to the "-max_depth" of lgs_options?

Thanks a lot :)

**Comment by moold** [comment]
If you use `lgs_options = -min_read_len 10k -max_read_len 150k -max_depth 60`, which means you will set `-min_read_len` to `10k`, if you use  `lgs_options = -max_read_len 150k -max_depth 60`, which means you do not set `-min_read_len`, so the `min_read_len` is 1k (default value).

**Comment by Zea1nfO** [comment]
> If you use `lgs_options = -min_read_len 10k -max_read_len 150k -max_depth 60`, which means you will set `-min_read_len` to `10k`, if you use `lgs_options = -max_read_len 150k -max_depth 60`, which means you do not set `-min_read_len`, so the `-min_read_len` is 1k (default value).
> 
> `min_read_len` does not make a big difference in polishing your genome if you have enough data, but if you only have <60x data, just set it to 1k, in order to use more data for polishing.

Thank you ,sir
Have a nice day
