### ISSUE TITLE
questions about make

### ISSUE THREAD

**Issue by wbglizhizhong** [Nextomics/NextPolish#5]
![image](https://user-images.githubusercontent.com/26796424/65476239-daedae00-deb4-11e9-9a57-67f63d87883f.png)
Dear sir,
       When I install the software, some errors appeared, could you give some suggestions. Thanks a lot!

Best,

**Comment by moold** [comment]
Please paste the errors, I can not fix errors without any info.

**Comment by moold** [comment]
What is your system and gcc version?

**Comment by wbglizhizhong** [comment]
> What is your system and gcc version?
Ubuntu 16.04, gcc is 5.4.0

**Comment by moold** [comment]
Hi, I have fixed it and will release an updated version, but by now, you can simply replace file: util/Makefile with this file [Makefile.zip](https://github.com/Nextomics/NextPolish/files/3650586/Makefile.zip) to fix this error.
