### ISSUE TITLE
Ploidy option in config file?

### ISSUE THREAD

**Issue by cizydorczyk** [Nextomics/NextPolish#59]
**Question or Expected behavior**
Is there an option (or can one be implemented) to specify ploidy for polishing in the config file? From what I have been able to gather from the documentation, I cannot find one unless I map reads myself and set 'ploidy = 1' directory to nextpolish1.py. I cannot find a way to set ploidy using the config file.

Thank you,
Conrad

**Comment by moold** [comment]
Hi, you can set `polish_options = -p {multithread_jobs} -ploidy 1`

**Comment by cizydorczyk** [comment]
I must have missed that on my own, thanks!
