### ISSUE TITLE
some errors

### ISSUE THREAD

**Issue by wbglizhizhong** [Nextomics/NextPolish#6]
![image](https://user-images.githubusercontent.com/26796424/65742532-2907e900-e123-11e9-9645-a68756e0aecc.png)
Dear sir,
the new one also showed some mistakes, please give some suggestions, and the system is ubuntu 16, gcc is 5.4.0, thanks a lot!

Best

**Comment by moold** [comment]
It seems your system lacks libbz2 library, and try: `sudo apt-get install libbz2-dev`
