### ISSUE TITLE
How to rerun a unfinished job ?

### ISSUE THREAD

**Issue by biozhangzhou** [Nextomics/NextPolish#60]
Hello Dr.Hu:
I have simply tryed to run the same command again as you writed in FAQ , but all the processes and results seems will be reproduce. 
why would it happen And what should I do to rerun a job ?

**Comment by moold** [comment]
If an error occurs when nextpolish is running, you can not solve it by re-running.

Pls ref [here](https://github.com/Nextomics/NextPolish/issues/new?assignees=&labels=&template=bug-or-error-report.md&title=) to provide more details.

**Comment by biozhangzhou** [comment]
Sorry , I have deleted all the failed log; But I am sure the problem in my job is about the server resource.
I may submited too many jobs. 
By the way, I noted the resource needs of  Nextpolish is very unbalance, it comsums a lot as we have set in the bwa part but comsums litter in the samtools part, that's why i submit another job when one job still running and then problems happen.

**Comment by moold** [comment]
This is caused by BWA and SamTools pipes, you can use `user-defined alignment pipelines`, as described in [here](https://nextpolish.readthedocs.io/en/latest/TUTORIAL.html#polishing-using-short-reads-only)
