### ISSUE TITLE
How many bases are corrected in each iteration?

### ISSUE THREAD

**Issue by slbai01** [Nextomics/NextPolish#61]
I polished the genome use `nextpolish1.py` script, and I'm not found any file contained the corrected base information, like `arrow` or `pilon` output `vcf` file.  It should be noted that I have not run it in single command mode `nextPolish run.cfg`, so I am not sure if this is a problem.

**Comment by moold** [comment]
You can use `-debug` option to trace changed bases and see #29 and [here](https://nextpolish.readthedocs.io/en/latest/OPTION.html) for more details.

**Comment by slbai01** [comment]
> You can use `-debug` option to trace changed bases and see #29 and [here](https://nextpolish.readthedocs.io/en/latest/OPTION.html) for more details.

Thanks for your quickly reply.  : )
