### ISSUE TITLE
The meaning of "Max_depth"

### ISSUE THREAD

**Issue by lilinzhou** [Nextomics/NextPolish#62]
What's the meaning of the max_depth parameter？The manual has already explained this parameter "use up to ${max_depth} fold reads data to polish. (default: 100)". But I am confused by "up to". Does this mean that only the position with more than 100 fold will be corrected, while the position with less than 100 fold will not be corrected?

**Comment by moold** [comment]
No, if your input data is about 1000x, NextPolish will only use ~100x data to do mapping and polishing. If your  input data is less than 100X, NextPolish only will use all data to do mapping and polishing.
