### ISSUE TITLE
lower case introduced after nanopolish

### ISSUE THREAD

**Issue by longzhangnation** [Nextomics/NextPolish#63]
I used nextpolish to polish my genome , and I find that the some lower letters are added to my genome after finishing it . So can you fix the bug ? bacause these letters will impact downstream analysis.

**Comment by moold** [comment]
This is not a bug, see [here](https://nextpolish.readthedocs.io/en/latest/OPTION.html#output), you can easily capitalize it using [seqkit seq -u](https://bioinf.shenwei.me/seqkit/)

**Comment by longzhangnation** [comment]
I used Pilon to polish my genome ,and the result is upper . So I think the Nextpolish will do that ,too . So I use it for my downstream analysis . When  I find the problem , At first I thought it was softmasked . Maybe you can  fix it because some one may use the polished genome for repeatmasking without checking it.
