### ISSUE TITLE
python2: ctg_cns.c:2787: find_sup_alns: Assertion `i != sup_aln->i' failed.

### ISSUE THREAD

**Issue by lurebgi** [Nextomics/NextPolish#66]
**Describe the bug**
I was running NextPolish/lib/nextpolish2.py

**Error message**
python2: ctg_cns.c:2787: find_sup_alns: Assertion `i != sup_aln->i' failed.

**Operating system**
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.9.2009 (Core)
Release:	7.9.2009
Codename:	Core

**GCC**
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/apps/gcc/10.2.0/libexec/gcc/x86_64-pc-linux-gnu/10.2.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: ../gcc-10.2.0/configure --prefix=/apps/gcc/10.2.0 --enable-multilib
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 10.2.0 (GCC)

**Python**
What version of Python are you using?
2.7.15

**NextPolish**
What version of NextPolish are you using?
v1.3.1

**To Reproduce** (Optional)
Steps to reproduce the behavior. Providing a minimal test dataset on which we can reproduce the behavior will generally lead to quicker turnaround time!

**Additional context** (Optional)

**Comment by lurebgi** [comment]
It was resolved by selecting the tag 'tp:A:P'.

**Comment by Johnsonzcode** [comment]
> It was resolved by selecting the tag 'tp:A:P'.

Sorry to reopen the thread, Could you explain in detail? Do you mean extracting the bam file by filtering the lines do not comtain `tp:A:P` record?

**Comment by lurebgi** [comment]
sorry, it has been a while, I can't remember the details.

**Comment by Johnsonzcode** [comment]
> > It was resolved by selecting the tag 'tp:A:P'.
> 
> Sorry to reopen the thread, Could you explain in detail? Do you mean extracting the bam file by filtering the lines do not comtain `tp:A:P` record?

For who meets the problem again, it is right to remove line do not comtain `tp:A:P`.
