### ISSUE TITLE
liblzma error

### ISSUE THREAD

**Issue by kishor2019** [Nextomics/NextPolish#69]
I have tried with the version that has been asked to use incase of error like "liblzma.so.0: cannot open shared object file". BUt the problem remain as the same. Can someone please help me to solve the issue? Thanks in advance.

**Comment by moold** [comment]
Pls provide more details as [here](https://github.com/Nextomics/NextPolish/issues/new?assignees=&labels=&template=bug-or-error-report.md&title=)

**Comment by moold** [comment]
I will close this issue, because you have opened another issue about the same QA.
