### ISSUE TITLE
erro occurred in test

### ISSUE THREAD

**Issue by LIFanAr** [Nextomics/NextPolish#7]
Dear NextPolish developer,

Thank you for providing us with such a nice tool.

However when I run the test in NextPolish folder, erro was occurred as following,

"File "../nextPolish", line 44
    print '\033[35mPlease update to the latest version: %s, current version: %s \033[0m' % (latest, ver)
                                                                                       ^
SyntaxError: invalid syntax"

I don't know why. Could you give some advices to me?

Thank you again.

Ar

**Comment by moold** [comment]
Hi, please check your python version using `python --version`. Currently, NextPolish only support python2.7, I will move it to python3 in the future.

**Comment by LIFanAr** [comment]
Thank you.

My python version is Python 3.7.3 now. I am not sure other software would rely on this version. So, how could I fix this problem?

**Comment by moold** [comment]
Maybe you can install [python2.7](https://www.python.org/downloads/release/python-2716/) in your personal directory.

**Comment by LIFanAr** [comment]
Thank you so much.

I went through that step. But, new error came out qsub the test task. 

"[ERROR] 2019-10-16 20:39:14,367 polish_genome failed: please check the following logs:
[ERROR] 2019-10-16 20:39:14,368 */NextPolish/test_data/01_rundir/00.score_chain/04.polish.ref.sh.work/polish_genome0/nextPolish.sh.e
[ERROR] 2019-10-16 20:39:14,368 */NextPolish/test_data/01_rundir/00.score_chain/04.polish.ref.sh.work/polish_genome1/nextPolish.sh.e"
____________________________________________
nextPolish.sh.e* details:
"Traceback (most recent call last):
  File "*/NextPolish/lib/nextPolish.py", line 83, in <module>
    P = CDLL(os.path.dirname(os.path.realpath(__file__)) + '/' + "nextPolish.so")
  File "*/NextPolish/lib/python2.7/ctypes/__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: liblzma.so.5: cannot open shared object file: No such file or directory"

**Comment by moold** [comment]
It seems your system lacks the [Liblzma.so.5](https://rpmfind.net/linux/rpm2html/search.php?query) lib, may be you should install it firstly.
