### ISSUE TITLE
Illumina, HiFi, and Nanopore -- best strategy?

### ISSUE THREAD

**Issue by StefanoLonardi** [Nextomics/NextPolish#71]
Thanks for your great tool. I have a HiFi-based assembly, and I wondering what data I should use to get the best polished assembly. I have Illumina reads, HiFi reads and Nanopore reads. What is you suggestion? Thanks in advance, Stefano

**Comment by StefanoLonardi** [comment]
There seem to be a mode "6" for hifi reads. Can I use it? 

```
...

[sgs_option]
sgs_fofn = ./sgs.fofn
sgs_options = -max_depth 100 -bwa

[lgs_option]
lgs_fofn = ./lgs.fofn
lgs_options = -min_read_len 5k -max_depth 100
lgs_minimap2_options = -x map-ont

[hifi_option]
hifi_fofn = ./hifi.fofn
hifi_options = -min_read_len 5k -max_depth 100
hifi_minimap2_options = -x map-pb
```

**Comment by moold** [comment]
Yes, you can use it.But `Nanopore reads`  may not be suitable for genomes assembly with hifi reads.You can try to polish it using  `Illumina reads` and `HiFi reads`.

**Comment by StefanoLonardi** [comment]
Thanks for your reply and for the tool. I realize that using Nanopore reads to correct a HiFi-based assembly is probably not a good idea. You should document mode "6" in your manual so people can take advantage of hifi reads for polishing.
