### ISSUE TITLE
make: *** [Makefile:18：all] 错误 2

### ISSUE THREAD

**Issue by WJT0925** [Nextomics/NextPolish#72]
make[3]: 进入目录“/home/jingtian/software/NextPolish/lib/htslib”
fatal: Not a git repository: ../../.git/modules/lib/htslib
fatal: Not a git repository: ../../.git/modules/lib/htslib
gcc -g -Wall -O2 -I.  -c -o cram/cram_io.o cram/cram_io.c
cram/cram_io.c:61:10: fatal error: lzma.h: 没有那个文件或目录
 #include <lzma.h>
          ^~~~~~~~
compilation terminated.
make[3]: *** [Makefile:121：cram/cram_io.o] 错误 1
make[3]: 离开目录“/home/jingtian/software/NextPolish/lib/htslib”
make[2]: *** [../../lib/htslib//htslib.mk:153：../../lib/htslib//libhts.a] 错误 2
make[2]: 离开目录“/home/jingtian/software/NextPolish/util/samtools”
make[1]: *** [Makefile:22：samtools_] 错误 2
make[1]: 离开目录“/home/jingtian/software/NextPolish/util”
make: *** [Makefile:18：all] 错误 2

**Error message**
/home/jingtian/software/NextPolish/test_data/01_rundir/00.lgs_polish/01.db_split.sh.work/db_split0/nextPolish.sh: 行 5: /home/jingtian/software/NextPolish/bin/seq_split: 没有那个文件或目录

**Operating system**
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 19.04
Release:	19.04
Codename:	disco

**GCC**
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/8/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 8.4.0-1ubuntu1~18.04' --with-bugurl=file:///usr/share/doc/gcc-8/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-8 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 8.4.0 (Ubuntu 8.4.0-1ubuntu1~18.04) 

**Python**
Python 3.8.3
**NextPolish**
nextPolish v1.3.1

**To Reproduce** (Optional)
./nextPolish test_data/run.cfg    just use the test data you give

**Comment by moold** [comment]
see #39
