### ISSUE TITLE
Samtools not finding libraries

### ISSUE THREAD

**Issue by Neato-Nick** [Nextomics/NextPolish#74]
**Describe the bug**
When running the nextPolish test data, I get a samtools error. I can also get this error by running bin/samtools from the NextPolish install dir. I tried both the CentOS release and the regular release

**Error message**
Paste the complete log message, include the main task log and failed subtask log.
The main task log is usually located  in your working directory and is named `pidXXX.log.info` and the main task log will tell you the failed subtask log in the last few lines, such as:
<pre>
[ERROR] 2021-06-10 20:14:46,017 db_split failed: please check the following logs:
[ERROR] 2021-06-10 20:14:46,453 <ins>~/NextPolish/test_data/01_rundir/00.lgs_polish/01.db_split.sh.work/db_split2/nextPolish.sh.e</ins>
~/NextPolish/bin/samtools: error while loading shared libraries: libhts.so.3: cannot open shared object file: No such file or directory

</pre>

**Operating system**
CentOS-7

**GCC**
What version of GCC are you using?
4.9.4

**Python**
What version of Python are you using?
You can use the command `python --version` to get it.

**NextPolish**
What version of NextPolish are you using?
nextPolish v1.3.1

**Additional context** (Optional)
I get the same error just running ~/NextPolish/bin/samtools

I had[ to configure samtools separately](https://github.com/Nextomics/NextPolish/issues/32#issuecomment-859230134) first because I cannot install curses. Maybe I missed something in configuration that caused that header to not get installed into the right place? What version of samtools does this depend on, I have a few different versions already installed I could use binaries from.

**Comment by moold** [comment]
NextPolish does not require a specific version of samtools, so you can copy samtools which you can run it without errors to ~/NextPolish/bin/, or you can use your own alignment pipeline, which does not require samtools if you have sorted bam files, see [here](https://nextpolish.readthedocs.io/en/latest/QSTART.html#quick-start) for an example.

**Comment by Neato-Nick** [comment]
Great, I was able to copy over a samtools 1.9 binary into NextPolish/bin and that worked perfectly. I'm happy if you Close this, issue, thank you!
