### ISSUE TITLE
liblzma.so.0 not found

### ISSUE THREAD

**Issue by gorliver** [Nextomics/NextPolish#77]
Hi Dr. Hu,
I ran the lastest NextPolish (centos6.9 version) and it stopped with this warning:
```
  File "/mnt/ufs18/home-034/tianti/software/nextpolish/NextPolish/lib/nextpolish1.py", line 84, in <module>
    P = CDLL(os.path.dirname(os.path.realpath(__file__)) + '/' + "nextpolish1.so")
  File "/mnt/home/tianti/anaconda3/lib/python3.8/ctypes/__init__.py", line 381, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: liblzma.so.0: cannot open shared object file: No such file or directory
```

Here is the output of `ldd nextpolish1.so`:
        linux-vdso.so.1 =>  (0x00007ffecb538000)
        /opt/software/impi/2018.3.222-iccifort-2018.3.222-GCC-7.3.0-2.30/lib64/libmpi.so (0x00002abe76fdd000)
        libpthread.so.0 => /usr/lib64/libpthread.so.0 (0x00002abe77c6c000)
        libm.so.6 => /usr/lib64/libm.so.6 (0x00002abe77e88000)
        libbz2.so.1 => /usr/lib64/libbz2.so.1 (0x00002abe7818a000)
        liblzma.so.0 => not found
        libz.so.1 => /opt/software/zlib/1.2.11-GCCcore-10.2.0/lib/libz.so.1 (0x00002abe76b71000)
        libc.so.6 => /usr/lib64/libc.so.6 (0x00002abe7839a000)
        librt.so.1 => /usr/lib64/librt.so.1 (0x00002abe78768000)
        libdl.so.2 => /usr/lib64/libdl.so.2 (0x00002abe78970000)
        libgcc_s.so.1 => /opt/software/GCCcore/10.2.0/lib64/libgcc_s.so.1 (0x00002abe76b8d000)
        /lib64/ld-linux-x86-64.so.2 (0x00002abe76b2d000)
The output of `ldd nextpolish2.so` is the same.

I downloaded the `nextpolish2.zip` from #33 and this one has the correct link for liblzma.so.0:
```
        linux-vdso.so.1 =>  (0x00007fff1f9a9000)
        /opt/software/impi/2018.3.222-iccifort-2018.3.222-GCC-7.3.0-2.30/lib64/libmpi.so (0x00002b2cf12ae000)
        libpthread.so.0 => /usr/lib64/libpthread.so.0 (0x00002b2cf1f3d000)
        libm.so.6 => /usr/lib64/libm.so.6 (0x00002b2cf2159000)
        libbz2.so.1 => /usr/lib64/libbz2.so.1 (0x00002b2cf245b000)
        liblzma.so.5 => /opt/software/XZ/5.2.5-GCCcore-10.2.0/lib/liblzma.so.5 (0x00002b2cf0e0b000)
        libz.so.1 => /opt/software/zlib/1.2.11-GCCcore-10.2.0/lib/libz.so.1 (0x00002b2cf0e34000)
        libc.so.6 => /usr/lib64/libc.so.6 (0x00002b2cf266b000)
        librt.so.1 => /usr/lib64/librt.so.1 (0x00002b2cf2a39000)
        libdl.so.2 => /usr/lib64/libdl.so.2 (0x00002b2cf2c41000)
        libgcc_s.so.1 => /opt/software/GCCcore/10.2.0/lib64/libgcc_s.so.1 (0x00002b2cf0e50000)
        /lib64/ld-linux-x86-64.so.2 (0x00002b2cf0de6000)
```

Do you have any suggestions to fix this problem?

Many thanks,
Goliver

**Comment by moold** [comment]
See [here](https://nextpolish.readthedocs.io/en/latest/QSTART.html#installation) and try another version. If you get this problem again, please refer to the issue template and provide  more detailes.

**Comment by gorliver** [comment]
That works! Thank you.
