### ISSUE TITLE
nextPolish: "shutil.Error: Cannot move a directory onto itself"

### ISSUE THREAD

**Issue by shankar2318** [Nextomics/NextPolish#78]
**Error**
I am actually not quite sure about the error. Since it seems like nextPolish is trying to overwrite the current directory but is not able to do it. 
Initially I tried to run the program as is without specifying a working directory since I assumed it would run in the directory where I have my `job.sh, run.cfg, sgs.fofn`. However, this was creating an issue where the `nextpolish` directory was being overwritten and a new directory `nextpolish.backup0` directory was being created where all the job files were being moved into. This also created an error where the program can't find the `run.cfg and sgs.fofn` since the original directory is being overwritten and a new directory with a different name is being created to house the job files. So, I specified a working directory using `workdir = /home/shankar2318/job_scripts/polish/nextpolish/` and `rewrite = no`. However, now I see a different error which is as follows:

**Error message**
<pre>
[INFO] 2021-08-21 01:40:40,401 start...
[INFO] 2021-08-21 01:40:40,403 logfile: pid65533.log.info
[WARNING] 2021-08-21 01:40:44,100 Delete task: 5 due to missing lgs_fofn.
[WARNING] 2021-08-21 01:40:44,101 Delete task: 5 due to missing lgs_fofn.
[WARNING] 2021-08-21 01:40:44,101 Delete task: 6 due to missing hifi_fofn.
[WARNING] 2021-08-21 01:40:44,101 Delete task: 6 due to missing hifi_fofn.
[INFO] 2021-08-21 01:40:44,101 scheduled tasks:
[1, 2, 1, 2]
[INFO] 2021-08-21 01:40:44,101 options: 
[INFO] 2021-08-21 01:40:44,101 {'polish_options': ' -p 5', 'rewrite': 0, 'job_prefix': 'nextPolish', 'job_type': 'local', 'hifi_minimap2_options': '-x map-pb', 'cluster_options': '', 'job-type': 'local', 'sgs_fofn': '/home/shankar2318/job_scripts/polish/nextpolish/sgs.fofn', 'snp_valid': '/home/shankar2318/job_scripts/polish/nextpolish//%02d.snp_valid', 'sgs_rm_nread': 1, 'kmer_count': '/home/shankar2318/job_scripts/polish/nextpolish//%02d.kmer_count', 'sgs_max_depth': '100', 'align_threads': '5', 'sgs_block_size': 500000000, 'lgs_max_read_len': '0', 'parallel_jobs': '6', 'multithread_jobs': '5', 'snp_phase': '/home/shankar2318/job_scripts/polish/nextpolish//%02d.snp_phase', 'genome': '/home/shankar2318/job_scripts/polish/polca/canu.fasta.PolcaCorrected.fa', 'lgs_read_type': '', 'genome_size': 1718365458L, 'workdir': '/home/shankar2318/job_scripts/polish/nextpolish/', 'cleantmp': 0, 'hifi_max_read_len': '0', 'hifi_block_size': '500M', 'hifi_min_read_len': '1k', 'sgs_align_options': 'bwa mem -p  -t 5', 'sgs_unpaired': '0', 'hifi_max_depth': '100', 'lgs_polish': '/home/shankar2318/job_scripts/polish/nextpolish//%02d.lgs_polish', 'sgs_use_duplicate_reads': 0, 'score_chain': '/home/shankar2318/job_scripts/polish/nextpolish//%02d.score_chain', 'task': [1, 2, 1, 2], 'lgs_max_depth': '100', 'lgs_block_size': '500M', 'lgs_minimap2_options': '-x map-ont', 'rerun': 3, 'hifi_polish': '/home/shankar2318/job_scripts/polish/nextpolish//%02d.hifi_polish', 'lgs_min_read_len': '1k'}
Traceback (most recent call last):
  File "/home/shankar2318/software/NextPolish/nextPolish", line 511, in <module>
    main(args)
  File "/home/shankar2318/software/NextPolish/nextPolish", line 354, in main
    shutil.move(cfg['workdir'], e)
  File "/usr/lib64/python2.7/shutil.py", line 297, in move
    raise Error, "Cannot move a directory '%s' into itself '%s'." % (src, dst)
shutil.Error: Cannot move a directory '/home/shankar2318/job_scripts/polish/nextpolish/' into itself '/home/shankar2318/job_scripts/polish/nextpolish/.backup0'.
</pre>

**Operating system**
<pre>
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.6.1810 (Core) 
Release:	7.6.1810
Codename:	Core
</pre>

**GCC**
<pre>
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC)
</pre>

**Python**
```
Python 2.7.5
```

**NextPolish**
```
nextPolish v1.3.1
```
I hope you can help me with this error. 
Thank you for your time.

**Comment by moold** [comment]
Try to set `workdir = /home/shankar2318/job_scripts/polish/nextpolish/workdir`
