### ISSUE TITLE
Nextpolish on slurm

### ISSUE THREAD

**Issue by aureliendejode** [Nextomics/NextPolish#79]
Hi,

I am trying to run Next Polish on a slurm cluster.
To do so I need to pass several info when I normally submit a job on the cluster, one of which is a flag precising the account.
So it looks like this: sbatch -A account script.sh

Is there a way to pass that -A flag to all the job submitted by the  nextPolish run.cfg command ?

Thanks

**Comment by moold** [comment]
Yes, try `cluster_option = -A account  --cpus-per-task={cpu} --mem-per-cpu={vf}`
