### ISSUE TITLE
What's the lowercase letters

### ISSUE THREAD

**Issue by lilinzhou** [Nextomics/NextPolish#8]
Hi,

I found that the genome contain some bases in lowercase letters after polishing. I would like to know what these lowercase letters represent, is it repeat sequence or corrected sequence by `Nextpolish`?

In addition, I also found that the genome is larger than the original genome after polishing (about 10Mb longer for a 400Mb genome). Did `NextPolish` made some extensions for the original genome using shortgun reads?

Best

**Comment by moold** [comment]
1.  The lowercase letters are low quality bases.
2. No, it means the assembly includes more deletion errors than insertion errors, so the genome size will larger than original after fixed more deletion errors.

**Comment by lilinzhou** [comment]
How about the lowercase letters in the output of `NextDenovo`? The original genome produced by `NextDenovo `also contained some lowercase letters.

**Comment by moold** [comment]
see [here](https://github.com/Nextomics/NextDenovo/blob/master/doc/OPTION.md)

**Comment by lilinzhou** [comment]
Sorry, I didn't notice. Many thanks!

**Comment by DengHAU** [comment]
Hi，all,

Genome had ‘N’ base after nextpolish, what's the N base means? The original assembly from long reads had no N base.

Thanks a lot!

**Comment by moold** [comment]
See FAQ vi.

**Comment by DengHAU** [comment]
Thanks !
