### ISSUE TITLE
Using Illumina reads containing "N" bases

### ISSUE THREAD

**Issue by cgjosephlee** [Nextomics/NextPolish#81]
**Question or Expected behavior**
I found my polished genome contained a few N bases. I do read the FAQ and found there are indeed some N bases in my illumina reads. And I see the release page saying NextPolish v1.3.1 deletes the reads containing N. So is it safe to use reads with a few Ns now, or I have to filter them by my self?

PS. I found >10% of my reads contained N, mostly just a single N. Total N ratio is less than 0.05%. I think I'll lose too many coverage if I remove all of them.

Thank you.

**Operating system**

**GCC**

**Python**

**NextPolish**
v1.3.1

**Additional context** (Optional)

**Comment by moold** [comment]
Hi, 
1. Yes,  is it safe to use reads with a few Ns using `NextPolish1.3.1`.
2. If you do not want to remove whole reads with Ns, You can trim the `N` tail or head.

**Comment by hungweichen0327** [comment]
Dear authors,
I used nextpolish1.4.1 but I still found my polished genome contained a few N bases. Do I need to filter  illumina reads containing N bases by myself?
