### ISSUE TITLE
Missing .stats file ... ?

### ISSUE THREAD

**Issue by josieparis** [Nextomics/NextPolish#82]
**Question or Expected behavior**
Hi there, thanks for a fantastic tool! I only have a quick question. Perhaps I'm missing something obvious. I ran nextpolish using alignments I already created outside of the main pipeline. I run nextpolish like so:
```
python nextpolish1.py -g $genome -t 1 -p 16 -s $bam > $MASTER/nextpolish_round1.tmp.fasta
```
The job completes and I have the polished genome, but I do not get a .stat file. Am I missing something? 

**Operating system**
CentOS-7

**GCC**
gcc (GCC) 7.3.0

**Python**
Python 3.5.5

**NextPolish**
v1.3.1

**Comment by moold** [comment]
Hi, the stat file will only be generated when you run the complete NextPolish pipeline,but you can use some public tools to get some statistics, such as [calN50](https://github.com/lh3/calN50)

**Comment by josieparis** [comment]
Thanks!
