### ISSUE TITLE
Some question about pacbio hifi data polish

### ISSUE THREAD

**Issue by xiaobaiymq** [Nextomics/NextPolish#85]
**Question or Expected behavior**
A clear and concise description of your question or what you expected to happen.

**Question or Expected behavior**
I first use hifiasm to get the haplotype assembly and then use Nextpolish to polish, but I found a change after polish.
At primary assembly,it is not have N
```
Mismatches	
# N's	0
# N's per 100 kbp	0

but in polish assembly，which have a lot of Mismatches
Mismatches	
# N's	40
# N's per 100 kbp	0.01
```

I don't kown this is normal

thanks

**Operating system**
LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.5.1804 (Core) 
Release:	7.5.1804
Codename:	Core

**GCC**
gcc 版本 4.8.5 20150623 (Red Hat 4.8.5-28) (GCC) 

**Python**
Python 3.8.5

**NextPolish**
nextPolish v1.3.0

**Additional context** (Optional)

**Comment by moold** [comment]
Could you paste your config file to here?

**Comment by xiaobaiymq** [comment]
This is my run.cfg
[General]
job_type = local  ## local, sge, pbs... (default: sge)
job_prefix = nextPolish1
task = best 
rewrite = no
rerun = 3 
parallel_jobs = 2
multithread_jobs = 3 
genome =xx.asm.hic.hap1.p_ctg.fa 
genome_size = auto 
workdir = ./rundir
polish_options = -p {multithread_jobs} 

[sgs_option] 
sgs_fofn = ./sgs.fofn 
sgs_options = -max_depth 100 -bwa

[lgs_option] 
lgs_fofn = ./lgs.fofn
lgs_options = -min_read_len 5k -max_depth 100
lgs_minimap2_options = -x map-pb

**Comment by moold** [comment]
see [here](https://nextpolish.readthedocs.io/en/latest/FAQ.html#why-does-the-contig-n50-of-polished-genome-become-shorter-or-why-does-the-polished-genome-contains-some-extra-n)

**Comment by xiaobaiymq** [comment]
I get, Is it necessary to remove N but how to remove N, and how to remove N if necessary

**Comment by moold** [comment]
1. Does the input `sgs.fofn` contains `N`?
2. Is the input `lgs_fofn` hifi data? If yes, you should use `hifi_option`, see [here](https://nextpolish.readthedocs.io/en/latest/TUTORIAL.html#polishing-using-short-reads-and-hifi-reads).
3. If the assembly was assembled from HiFiasm, there is not much need to do polishing, because HiFiasm already include an error-correction step.

**Comment by xiaobaiymq** [comment]
Thank you very much ,I get you
