### ISSUE TITLE
Can I use the RNAseq data for genome polishing?

### ISSUE THREAD

**Issue by CGsTree** [Nextomics/NextPolish#86]
In plion, I found some people using RNAseq data for genome polishing.
link:
https://www.biostars.org/p/380941/
https://github.com/broadinstitute/pilon/issues/50
Please tell me if you recommend using rnaseq data in genome Polish?

**Comment by moold** [comment]
I have not tried also not recommend.

**Comment by CGsTree** [comment]
> I have not tried also not recommend.

Thank you very much, thank you for making such great software.
谢谢大哥🙏
