### ISSUE TITLE
job_type = local

### ISSUE THREAD

**Issue by shehongbing** [Nextomics/NextPolish#9]
HI, I test the nextpolish on local, but it does not work. And the error is 
db_split failed: please check the following logs:
[ERROR] 2019-11-15 10:10:16,795 */NextPolish/test_data/01_rundir/00.score_chain/01.db_split.sh.work/db_split0/nextPolish.sh.e
[ERROR] 2019-11-15 10:10:16,795 */NextPolish/test_data/01_rundir/00.score_chain/01.db_split.sh.work/db_split1/nextPolish.sh.e
[ERROR] 2019-11-15 10:10:16,795 */NextPolish/test_data/01_rundir/00.score_chain/01.db_split.sh.work/db_split2/nextPolish.sh.e

**Comment by moold** [comment]
As the log says, check log file: `/NextPolish/test_data/01_rundir/00.score_chain/01.db_split.sh.work/db_split0/nextPolish.sh.e`.
