### ISSUE TITLE
How NextPolish v1.4 treat gap in genome ?

### ISSUE THREAD

**Issue by Johnsonzcode** [Nextomics/NextPolish#94]
**Question or Expected behavior**
My genome contains 10 gap with each 100 bp, and polished genome contains no gap and became shorter.
So, How NextPolish v1.4 treat gap in genome ?

**Operating system**
Linux pbsnode01 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64  GNU/Linux

**GCC**
gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC)

**Python**
Python 2.7.13 :: Continuum Analytics, Inc.

**NextPolish**
nextPolish v1.4.0

**Additional context** (Optional)

**Comment by moold** [comment]
see [limitations](https://nextpolish.readthedocs.io/en/latest/QSTART.html#limitations)
