### ISSUE TITLE
NextPolish license and distribution of source code

### ISSUE THREAD

**Issue by seb45tian** [Nextomics/NextPolish#96]
Hi there,

NextPolish makes use of several other codes using the MIT and/or GPLv3 licence, e.g. 
- samtools -> MIT
- htslib -> MIT
- minimap2 -> MIT
- bwa -> GPLv3, MIT

This github repository does not (directly) provide any source code: not for NextPolish itself, its Makefile or any other used 3rd party utility. Instead, you provide releases containing the source code for 3rd party utilities, a Makefile and a pre-compiled nextPolish static binary as well as pre-compiled shared libraries (calgs.so, nextpolish1.so, nextpolish2.so). 

My questions are
- a) Why do you distribute the software this way?
- b) You added a GPLv3 License file to your releases. Are you sure you are not also required (via the GPLv3) to also make the source code to nextPolish and its libraries available to the public?

Many thanks!

**Comment by moold** [comment]
Hi, I'm sorry for this question bothers you or anyone else with a similar concerns, but it's a long story and I work for a commercial company, so I don't want to say too much about it.
However, 
If you (or others) want the source code for nextPolish, I'd be happy to email it to you, after receiving your request email sent via a educational mail. 
You can delete samtools or third-party software in the nextPolish directory, and then follow [here](https://nextpolish.readthedocs.io/en/latest/) to use your own alignment pipeline, and then only use NextPolish to polish the genome. The precision of the polished genome is the same as the default.
I'm not familiar with open source licenses, I randomly chose the GPL license after someone asked me to release the license, so if you have a better option, I can replace and update it.
