### ISSUE TITLE
gap filling effects?

### ISSUE THREAD

**Issue by EugeneKim76** [Nextomics/NextPolish#98]
**NextPolish**
What version of NextPolish are you using? 1.3.1
You can use the command `nextPolish -v` to get it.

Dear all,
I polished my assembly using long reads and nextpolish.  
There are 7 small gaps (each length is 13Ns) in my assembly.
I checked the manual, and identified that it is recommended to split the assemblies at the gaps, then polish it using nextpolish.
However, I found the polishing step resulted in filling all the gaps. 
How can I understand the result? 
I'm so confused since it is considered that some researchers are using nextpolish as a gap filling tool. 
There are some examples on googlescholar.  (search by keywords : nextpolish, gap filling).
Best,

**Comment by moold** [comment]
For gaps that some reads can span, nextPolish can use these spanned reads to close those gaps. For other gaps, nextPolish may cause undefined behavior.

**Comment by EugeneKim76** [comment]
Dear moold,
Thanks for your quickly reply
Best,
